/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
public class Copaus1cDfhcommareaDto {

    private String wsPgmAuthDtl;

    private String wsPgmAuthSmry;

    private String wsPgmAuthFraud;

    private String wsCicsTranid;

    private String wsMessage;

    private String wsErrFlg;

    private Integer wsAcctId;

    private String wsAuthKey;

    private BigDecimal wsAuthAmt;

    private String wsAuthDate;

    private String wsAuthTime;

    private String declCode;

    private String declDesc;

    private String psbName;

    private Integer pautPcbNum;

    private String imsReturnCode;

    private Integer wsFrdAcctId;

    private Integer wsFrdCustId;

    private String wsFraudAuthRecord;

    private String wsFrdAction;

    private String wsFrdUpdateStatus;

    private String wsFrdActMsg;

    private String cdemoCpvdPauSelFlg;

    private String cdemoCpvdPauSelected;

    private String cdemoCpvdPaukeyPrevPg;

    private String cdemoCpvdPaukeyLast;

    private Integer cdemoCpvdPageNum;

    private String cdemoCpvdNextPageFlg;

    private String cdemoCpvdAuthKeys;

    private String cdemoCpvdFraudData;

}