/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
public class CotrtupcDfhcommareaDto {

    private Integer wsRespCd;

    private Integer wsReasCd;

    private String wsTranid;

    private String wsUctrans;

    private String wsEditVariableName;

    private String wsEditAlphanumOnly;

    private Integer wsEditAlphanumLength;

    private String wsEditAlphanumOnlyFlags = "N/A";

    private Integer wsDispSqlcode;

    private Integer wsStringMid;

    private Integer wsStringLen;

    private String wsStringOut;

    private String wsEditTtypFlag = "N/A";

    private String wsEditDescFlags = "N/A";

    private String wsEditDateXYear;

    private String wsEditDateMonth;

    private String wsEditDateDay;

    private Integer wsEditNumeric2;

    private String wsEditAlphanumeric2;

    private String ttupUpdateTtypType;

    private String ttupUpdateTtypTypeDesc;

    private String wsInfoMsg;

    private String wsReturnMsg;

    private String litThispgm;

    private String litThistranid;

    private String litThismapset;

    private String litThismap;

    private String litAdminpgm;

    private String litAdmintranid;

    private String litListtpgm;

    private String litUpper;

    private String litLower;

    private String litNumbers;

    private String litAllAlphanumFrom;

    private String litAlphanumSpacesTo;

    private String ttupChangeAction;

    private String ttupOldTtypType;

    private String ttupOldTtypTypeDesc;

    private String ttupNewTtypType;

    private String ttupNewTtypTypeDesc;

    private String wsCommarea;

}