/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.batch;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * JCL step conditions (#3622), against the return codes of the steps before.
 *   COND=(code,op[,step]),... bypasses the step when ANY test holds: `code op RC` for the named step,
 *   else for every step before (COND=(4,LT): bypass if 4 < some RC). EVEN / ONLY concern abends, which
 *   stop a Spring Batch job: they are not evaluated here.
 *   IF (expression) THEN: RC, step.RC, relational operators, AND / & / OR / | / NOT; RC alone is the
 *   highest return code so far.
 */
public final class JclConditions {

    private static final Pattern TEST = Pattern.compile("(\\d+)\\s*,\\s*(GT|GE|EQ|LT|LE|NE)\\s*(?:,\\s*([A-Z0-9#@$.]+))?");

    private JclConditions() {
    }

    public static boolean bypass(String cond, Map<String, Integer> rcs) {
        if (cond == null || rcs.isEmpty()) {
            return false;
        }
        Matcher m = TEST.matcher(cond.toUpperCase());
        while (m.find()) {
            int code = Integer.parseInt(m.group(1));
            String op = m.group(2);
            if (m.group(3) != null) {
                Integer rc = rcs.get(m.group(3));
                if (rc != null && compare(code, op, rc)) {
                    return true;
                }
            } else {
                for (int rc : rcs.values()) {
                    if (compare(code, op, rc)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    static boolean compare(int left, String op, int right) {
        return switch (op) {
            case "GT", ">" -> left > right;
            case "GE", ">=" -> left >= right;
            case "EQ", "=" -> left == right;
            case "LT", "<" -> left < right;
            case "LE", "<=" -> left <= right;
            case "NE", "\u00ac=", "^=" -> left != right;
            default -> throw new IllegalArgumentException("unknown operator " + op);
        };
    }

    /** Whether an IF expression holds (true when there is none). */
    public static boolean holds(String expression, Map<String, Integer> rcs) {
        if (expression == null || expression.isBlank()) {
            return true;
        }
        return new Parser(tokens(expression), rcs).or();
    }

    private static List<String> tokens(String text) {
        Matcher m = Pattern.compile("[A-Z0-9#@$]+(?:\\.[A-Z0-9#@$]+)*|>=|<=|\u00ac=|\\^=|[=<>()&|\u00ac]")
                .matcher(text.toUpperCase());
        List<String> out = new ArrayList<>();
        while (m.find()) {
            out.add(m.group());
        }
        return out;
    }

    private static final class Parser {
        private final List<String> t;
        private final Map<String, Integer> rcs;
        private int i;

        Parser(List<String> t, Map<String, Integer> rcs) {
            this.t = t;
            this.rcs = rcs;
        }

        private String peek() {
            return i < t.size() ? t.get(i) : "";
        }

        boolean or() {
            boolean v = and();
            while (peek().equals("OR") || peek().equals("|")) {
                i++;
                v = and() || v;
            }
            return v;
        }

        boolean and() {
            boolean v = not();
            while (peek().equals("AND") || peek().equals("&")) {
                i++;
                v = not() && v;
            }
            return v;
        }

        boolean not() {
            if (peek().equals("NOT") || peek().equals("\u00ac")) {
                i++;
                return !not();
            }
            if (peek().equals("(")) {
                i++;
                boolean v = or();
                if (peek().equals(")")) {
                    i++;
                }
                return v;
            }
            return relation();
        }

        boolean relation() {
            String left = t.get(i++);
            if (!left.endsWith("RC")) {
                return !left.contains("ABEND");  // ABEND / step.ABEND: no abended step continues a Spring Batch job
            }
            String op = t.get(i++);
            int right = Integer.parseInt(t.get(i++));
            int rc = left.equals("RC") ? rcs.values().stream().mapToInt(Integer::intValue).max().orElse(0)
                    : rcs.getOrDefault(left.substring(0, left.length() - 3), 0);
            return compare(rc, op, right);
        }
    }
}
