/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-genapp at commit f6f3f4b2580d31b7d8dcc31ce3e3676f4cceaaaa,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto.contract;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

/**
 * COBOL record CA-ERROR-MSG (base/src/lgacdb01.cbl), 99 bytes, from GitGalaxy's verified skeleton.
 * The COMMAREA Lgstsq receives, as passed by LINK at base/src/lgacdb01.cbl:316, LINK at base/src/lgacdb01.cbl:322.
 * Record fields field testing: field-tested (6 public / 0 private estates).
 */
@Data
@NoArgsConstructor
public class Lgacdb01CaErrorMsg {

    // CA-DATA: PIC X(90), offset 9, 90 bytes (base/src/lgacdb01.cbl)
    private String caData;

}