/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto.contract;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

/**
 * COBOL record SUBPGM-PARMS (src/base/cobol_src/BNK1CCS.cbl), 261 bytes, from GitGalaxy's verified skeleton.
 * The COMMAREA Crecust receives, as passed by LINK at src/base/cobol_src/BNK1CCS.cbl:976.
 * Record fields field testing: field-tested (6 public / 0 private estates).
 */
@Data
@NoArgsConstructor
public class Bnk1ccsSubpgmParms {

    // SUBPGM-EYECATCHER: PIC X(4), offset 0, 4 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private String subpgmEyecatcher;

    // SUBPGM-SORTCODE: PIC 9(6) DISPLAY, offset 4, 6 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private Integer subpgmSortcode;

    // SUBPGM-NUMBER: PIC 9(10) DISPLAY, offset 10, 10 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private Long subpgmNumber;

    // SUBPGM-NAME: PIC X(60), offset 20, 60 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private String subpgmName;

    // SUBPGM-ADDRESS: PIC X(160), offset 80, 160 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private String subpgmAddress;

    // SUBPGM-DATE-OF-BIRTH: PIC 9(8), offset 240, 8 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private Integer subpgmDateOfBirth;

    // SUBPGM-CREDIT-SCORE: PIC 999, offset 248, 3 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private Integer subpgmCreditScore;

    // SUBPGM-CS-REVIEW-DATE: PIC 9(8), offset 251, 8 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private Integer subpgmCsReviewDate;

    // SUBPGM-SUCCESS: PIC X, offset 259, 1 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private String subpgmSuccess;

    // SUBPGM-FAIL-CODE: PIC X, offset 260, 1 bytes (src/base/cobol_src/BNK1CCS.cbl)
    private String subpgmFailCode;

}