/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto.contract;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

/**
 * COBOL record ABNDINFO-REC (src/base/cobol_src/BNKMENU.cbl), 681 bytes, from GitGalaxy's verified skeleton.
 * The COMMAREA Abndproc receives, as passed by LINK at src/base/cobol_src/BNKMENU.cbl:225, LINK at src/base/cobol_src/BNKMENU.cbl:337, LINK at src/base/cobol_src/BNKMENU.cbl:441, LINK at src/base/cobol_src/BNKMENU.cbl:513, LINK at src/base/cobol_src/BNKMENU.cbl:586, LINK at src/base/cobol_src/BNKMENU.cbl:659, LINK at src/base/cobol_src/BNKMENU.cbl:732, LINK at src/base/cobol_src/BNKMENU.cbl:805, LINK at src/base/cobol_src/BNKMENU.cbl:878, LINK at src/base/cobol_src/BNKMENU.cbl:952, LINK at src/base/cobol_src/BNKMENU.cbl:1034, LINK at src/base/cobol_src/BNKMENU.cbl:1109, LINK at src/base/cobol_src/BNKMENU.cbl:1186, LINK at src/base/cobol_src/BNKMENU.cbl:1265.
 * Record fields field testing: field-tested (6 public / 0 private estates).
 */
@Data
@NoArgsConstructor
public class BnkmenuAbndinfoRec {

    // ABND-UTIME-KEY: PIC S9(15) COMP-3, offset 0, 8 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private Long abndUtimeKey;

    // ABND-TASKNO-KEY: PIC 9(4), offset 8, 4 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private Integer abndTasknoKey;

    // ABND-APPLID: PIC X(8), offset 12, 8 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private String abndApplid;

    // ABND-TRANID: PIC X(4), offset 20, 4 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private String abndTranid;

    // ABND-DATE: PIC X(10), offset 24, 10 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private String abndDate;

    // ABND-TIME: PIC X(8), offset 34, 8 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private String abndTime;

    // ABND-CODE: PIC X(4), offset 42, 4 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private String abndCode;

    // ABND-PROGRAM: PIC X(8), offset 46, 8 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private String abndProgram;

    // ABND-RESPCODE: PIC S9(8) DISPLAY, offset 54, 9 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private Integer abndRespcode;

    // ABND-RESP2CODE: PIC S9(8) DISPLAY, offset 63, 9 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private Integer abndResp2Code;

    // ABND-SQLCODE: PIC S9(8) DISPLAY, offset 72, 9 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private Integer abndSqlcode;

    // ABND-FREEFORM: PIC X(600), offset 81, 600 bytes (src/base/cobol_copy/ABNDINFO.cpy)
    private String abndFreeform;

}