/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-genapp at commit f6f3f4b2580d31b7d8dcc31ce3e3676f4cceaaaa,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.messaging;

import java.util.Optional;

/** CICS transient data (#3620): WRITEQ / READQ / DELETEQ TD, routed per destination (RoutingTransientData). */
public interface TransientData {

    void write(String queue, String record);

    /** READQ TD: destructive, first in first out; empty when the queue is (QZERO). */
    Optional<String> read(String queue);

    void delete(String queue);
}
