/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * ⚠️ AUTO-GENERATED MOCK SERVICE
 * This module intercepts unresolved COBOL calls to 'BYGG_OPP_BEREGNINGS_VEDLEGG_SEGMENT'.
 * It allows the Spring Context to load and the AI Agent to write code
 * without crashing due to missing dependencies.
 */
@Service
public class ByggOppBeregningsVedleggSegmentService {
    private static final Logger log = LoggerFactory.getLogger(ByggOppBeregningsVedleggSegmentService.class);

    public void executeDummyCall() {
        log.warn("Mock Service ByggOppBeregningsVedleggSegmentService was invoked. Implementation missing.");
    }
}
