/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

/**
 * HANDLE AID mapping (field testing: field-tested (6 public / 0 private estates)):
 *   HANDLE AID at line 127: PF1 -> PF1
 *   HANDLE AID at line 127: PF2 -> PF2
 *
 * Screens (#3619): none resolved.
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:145: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:156: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:318: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:321: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:383: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:386: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:451: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:455: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:476: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:480: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:495: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001N51 (mapset S001N53) at src/GML/R001N501.pli:499: no single BMS source defines it (candidates: none in the repository)
 */
@Service
@Transactional
@RequiredArgsConstructor
public class SrcGmlR001n501Service {

    private static final Logger log = LoggerFactory.getLogger(SrcGmlR001n501Service.class);

    private final ObjectProvider<SrcGmlR0010490Service> srcGmlR0010490Service;
    private final ObjectProvider<SrcGmlR0010301Service> srcGmlR0010301Service;
    private final ObjectProvider<SrcGmlR0010401Service> srcGmlR0010401Service;

    public void executeSrcGmlR001n501(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for src__GML__R001N501");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public void handleLink() {
        log.info("SrcGmlR001n501: handleLink");
    }

    /** EXEC CICS LINK PROGRAM(R0010490) at src/GML/R001N501.pli:442.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0010490() {
        srcGmlR0010490Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010301) at src/GML/R001N501.pli:165. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcGmlR0010301() {
        srcGmlR0010301Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010401) at src/GML/R001N501.pli:172, src/GML/R001N501.pli:354. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcGmlR0010401() {
        srcGmlR0010401Service.getObject().handleLink();
    }

    /**
     * EXEC CICS SYNCPOINT ROLLBACK at src/GML/R001N501.pli:390 (paragraph UTGANG): rolls the unit of work back.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void rollbackL390() {
        throw new UnitOfWorkRollbackException("SRC__GML__R001N501", "src/GML/R001N501.pli:390");
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/GML/R001N501.pli:129 (paragraph R001N5) routes ERROR to FEILBEH.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL129(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL FEILBEH at line 129", e);
        // TODO: port paragraph FEILBEH's logic
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/GML/R001N501.pli:361 (paragraph UTGANG) routes ERROR to ABEND.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL361(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL ABEND at line 361", e);
        // TODO: port paragraph ABEND's logic
    }

    /**
     * EXEC CICS ABEND ABCODE(FEIL) at src/GML/R001N501.pli:400 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendFeilL400() {
        throw new CicsAbendException("FEIL", "SRC__GML__R001N501", "src/GML/R001N501.pli:400");
    }

}