/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

/**
 * HANDLE AID mapping (field testing: field-tested (6 public / 0 private estates)):
 *   HANDLE AID at line 75: PF1 -> PF1
 *   HANDLE AID at line 75: PF2 -> PF2
 *
 * Screens (#3619): none resolved.
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:89: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001081 (mapset S001083) at src/GML/R0010801.pli:101: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001201 (mapset S001203) at src/GML/R0010801.pli:104: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:312: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:315: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:319: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:322: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:367: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:428: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001081 (mapset S001083) at src/GML/R0010801.pli:431: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:504: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:508: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:515: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:519: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:543: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:547: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:554: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:558: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:575: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001081 (mapset S001083) at src/GML/R0010801.pli:579: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:586: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/GML/R0010801.pli:590: no single BMS source defines it (candidates: none in the repository)
 */
@Service
@Transactional
@RequiredArgsConstructor
public class SrcGmlR0010801Service {

    private static final Logger log = LoggerFactory.getLogger(SrcGmlR0010801Service.class);

    private final ObjectProvider<SrcGmlR0010490Service> srcGmlR0010490Service;
    private final ObjectProvider<SrcGmlR0010301Service> srcGmlR0010301Service;
    private final ObjectProvider<SrcGmlR0010401Service> srcGmlR0010401Service;

    public void executeSrcGmlR0010801(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for src__GML__R0010801");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public void handleLink() {
        log.info("SrcGmlR0010801: handleLink");
    }

    /** EXEC CICS LINK PROGRAM(R0010490) at src/GML/R0010801.pli:493.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0010490() {
        srcGmlR0010490Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010301) at src/GML/R0010801.pli:119, src/GML/R0010801.pli:134. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcGmlR0010301() {
        srcGmlR0010301Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010401) at src/GML/R0010801.pli:126, src/GML/R0010801.pli:141, src/GML/R0010801.pli:396. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcGmlR0010401() {
        srcGmlR0010401Service.getObject().handleLink();
    }

    /**
     * EXEC CICS SYNCPOINT ROLLBACK at src/GML/R0010801.pli:435 (paragraph UTGANG): rolls the unit of work back.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void rollbackL435() {
        throw new UnitOfWorkRollbackException("SRC__GML__R0010801", "src/GML/R0010801.pli:435");
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/GML/R0010801.pli:73 (paragraph R00108) routes ERROR to FEILBEH.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL73(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL FEILBEH at line 73", e);
        // TODO: port paragraph FEILBEH's logic
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/GML/R0010801.pli:403 (paragraph UTGANG) routes ERROR to ABEND.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL403(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL ABEND at line 403", e);
        // TODO: port paragraph ABEND's logic
    }

    /**
     * EXEC CICS ABEND ABCODE(FEIL) at src/GML/R0010801.pli:445 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendFeilL445() {
        throw new CicsAbendException("FEIL", "SRC__GML__R0010801", "src/GML/R0010801.pli:445");
    }

}