/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
@RequiredArgsConstructor
public class SrcGmlR0014001Service {

    private static final Logger log = LoggerFactory.getLogger(SrcGmlR0014001Service.class);

    private final ObjectProvider<SrcGmlR0014101Service> srcGmlR0014101Service;
    private final ObjectProvider<SrcGmlR0014201Service> srcGmlR0014201Service;
    private final ObjectProvider<SrcGmlR0014251Service> srcGmlR0014251Service;
    private final ObjectProvider<SrcGmlR0014301Service> srcGmlR0014301Service;
    private final ObjectProvider<SrcGmlR0014370Service> srcGmlR0014370Service;
    private final ObjectProvider<SrcGmlR0014401Service> srcGmlR0014401Service;
    private final ObjectProvider<SrcGmlR0014470Service> srcGmlR0014470Service;
    private final ObjectProvider<SrcGmlR0014501Service> srcGmlR0014501Service;
    private final ObjectProvider<SrcGmlR0014601Service> srcGmlR0014601Service;
    private final ObjectProvider<SrcGmlR0014701Service> srcGmlR0014701Service;
    private final ObjectProvider<SrcGmlR0014801Service> srcGmlR0014801Service;

    public void executeSrcGmlR0014001(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for src__GML__R0014001");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public void handleLink() {
        log.info("SrcGmlR0014001: handleLink");
    }

    /** EXEC CICS LINK PROGRAM(R0014101) at src/GML/R0014001.pli:229.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014101() {
        srcGmlR0014101Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014201) at src/GML/R0014001.pli:238, src/GML/R0014001.pli:275, src/GML/R0014001.pli:402, src/GML/R0014001.pli:465, src/GML/R0014001.pli:549.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014201() {
        srcGmlR0014201Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014251) at src/GML/R0014001.pli:285, src/GML/R0014001.pli:412, src/GML/R0014001.pli:438, src/GML/R0014001.pli:475, src/GML/R0014001.pli:559.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014251() {
        srcGmlR0014251Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014301) at src/GML/R0014001.pli:312.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014301() {
        srcGmlR0014301Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014370) at src/GML/R0014001.pli:687.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014370() {
        srcGmlR0014370Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014401) at src/GML/R0014001.pli:294, src/GML/R0014001.pli:371, src/GML/R0014001.pli:421, src/GML/R0014001.pli:484, src/GML/R0014001.pli:518, src/GML/R0014001.pli:568.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014401() {
        srcGmlR0014401Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014470) at src/GML/R0014001.pli:633, src/GML/R0014001.pli:656.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014470() {
        srcGmlR0014470Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014501) at src/GML/R0014001.pli:363, src/GML/R0014001.pli:509.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014501() {
        srcGmlR0014501Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014601) at src/GML/R0014001.pli:320.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014601() {
        srcGmlR0014601Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014701) at src/GML/R0014001.pli:336.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014701() {
        srcGmlR0014701Service.getObject().handleLink();
    }

    /** EXEC CICS LINK PROGRAM(R0014801) at src/GML/R0014001.pli:352.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcGmlR0014801() {
        srcGmlR0014801Service.getObject().handleLink();
    }

}