/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

/**
 * HANDLE AID mapping (field testing: field-tested (6 public / 0 private estates)):
 *   HANDLE AID at line 126: PF1 -> PF1
 *   HANDLE AID at line 126: PF2 -> PF2
 *   HANDLE AID at line 126: PF7 -> PF7
 *   HANDLE AID at line 126: PF8 -> PF8
 *
 * Screens (#3619): none resolved.
 * TODO: SEND MAP S001U82 (mapset S001U83) at src/R001U801.pli:143: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U83 (mapset S001U83) at src/R001U801.pli:151: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/R001U801.pli:159: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:167: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001U81 (mapset S001U83) at src/R001U801.pli:182: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001U82 (mapset S001U83) at src/R001U801.pli:188: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001U83 (mapset S001U83) at src/R001U801.pli:194: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001201 (mapset S001203) at src/R001U801.pli:200: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:548: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U82 (mapset S001U83) at src/R001U801.pli:555: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U83 (mapset S001U83) at src/R001U801.pli:562: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/R001U801.pli:568: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:577: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U82 (mapset S001U83) at src/R001U801.pli:582: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U83 (mapset S001U83) at src/R001U801.pli:587: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/R001U801.pli:592: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:619: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U82 (mapset S001U83) at src/R001U801.pli:642: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U83 (mapset S001U83) at src/R001U801.pli:667: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001201 (mapset S001203) at src/R001U801.pli:694: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:764: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001U81 (mapset S001U83) at src/R001U801.pli:767: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:838: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:842: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:880: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:884: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:912: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001U81 (mapset S001U83) at src/R001U801.pli:916: no single BMS source defines it (candidates: none in the repository)
 */
@Service
@Transactional
@RequiredArgsConstructor
public class SrcR001u801Service {

    private static final Logger log = LoggerFactory.getLogger(SrcR001u801Service.class);

    private final ObjectProvider<SrcR0010490Service> srcR0010490Service;
    private final ObjectProvider<SrcR0010301Service> srcR0010301Service;
    private final ObjectProvider<SrcR0010401Service> srcR0010401Service;

    public void executeSrcR001u801(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for src__R001U801");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public void handleLink() {
        log.info("SrcR001u801: handleLink");
    }

    /** EXEC CICS LINK PROGRAM(R0010490) at src/R001U801.pli:827.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcR0010490() {
        srcR0010490Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010301) at src/R001U801.pli:225. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcR0010301() {
        srcR0010301Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010401) at src/R001U801.pli:246, src/R001U801.pli:730. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcR0010401() {
        srcR0010401Service.getObject().handleLink();
    }

    /**
     * EXEC CICS SYNCPOINT ROLLBACK at src/R001U801.pli:771 (paragraph UTGANG): rolls the unit of work back.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void rollbackL771() {
        throw new UnitOfWorkRollbackException("SRC__R001U801", "src/R001U801.pli:771");
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/R001U801.pli:125 (paragraph R001U8) routes ERROR to FEILBEH.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL125(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL FEILBEH at line 125", e);
        // TODO: port paragraph FEILBEH's logic
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/R001U801.pli:739 (paragraph UTGANG) routes ERROR to ABEND.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL739(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL ABEND at line 739", e);
        // TODO: port paragraph ABEND's logic
    }

    /**
     * EXEC CICS ABEND ABCODE(FEIL) at src/R001U801.pli:781 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendFeilL781() {
        throw new CicsAbendException("FEIL", "SRC__R001U801", "src/R001U801.pli:781");
    }

}