/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

/**
 * HANDLE AID mapping (field testing: field-tested (6 public / 0 private estates)):
 *   HANDLE AID at line 50: PF1 -> PF1
 *   HANDLE AID at line 50: PF2 -> PF2
 *
 * Screens (#3619): none resolved.
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:64: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001111 (mapset S001113) at src/R0011101.pli:75: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:128: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:134: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:136: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:198: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001111 (mapset S001113) at src/R0011101.pli:201: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:261: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:265: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:286: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:290: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:304: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001111 (mapset S001113) at src/R0011101.pli:308: no single BMS source defines it (candidates: none in the repository)
 */
@Service
@Transactional
@RequiredArgsConstructor
public class SrcR0011101Service {

    private static final Logger log = LoggerFactory.getLogger(SrcR0011101Service.class);

    private final ObjectProvider<SrcR0010490Service> srcR0010490Service;
    private final ObjectProvider<SrcR0010301Service> srcR0010301Service;
    private final ObjectProvider<SrcR0010401Service> srcR0010401Service;

    public void executeSrcR0011101(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for src__R0011101");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public void handleLink() {
        log.info("SrcR0011101: handleLink");
    }

    /** EXEC CICS LINK PROGRAM(R0010490) at src/R0011101.pli:253.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void linkSrcR0010490() {
        srcR0010490Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010301) at src/R0011101.pli:83. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcR0010301() {
        srcR0010301Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010401) at src/R0011101.pli:90, src/R0011101.pli:166. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcR0010401() {
        srcR0010401Service.getObject().handleLink();
    }

    /**
     * EXEC CICS SYNCPOINT ROLLBACK at src/R0011101.pli:205 (paragraph UTGANG): rolls the unit of work back.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void rollbackL205() {
        throw new UnitOfWorkRollbackException("SRC__R0011101", "src/R0011101.pli:205");
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/R0011101.pli:48 (paragraph R00111) routes ERROR to FEILBEH.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL48(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL FEILBEH at line 48", e);
        // TODO: port paragraph FEILBEH's logic
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/R0011101.pli:173 (paragraph UTGANG) routes ERROR to ABEND.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL173(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL ABEND at line 173", e);
        // TODO: port paragraph ABEND's logic
    }

    /**
     * EXEC CICS ABEND ABCODE(FEIL) at src/R0011101.pli:215 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendFeilL215() {
        throw new CicsAbendException("FEIL", "SRC__R0011101", "src/R0011101.pli:215");
    }

}