/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

/**
 * HANDLE AID mapping (field testing: field-tested (6 public / 0 private estates)):
 *   HANDLE AID at line 102: PF2 -> PF2
 *
 * Screens (#3619): none resolved.
 * TODO: SEND MAP S001831 (mapset S001833) at src/R0011831.pli:118: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001831 (mapset S001833) at src/R0011831.pli:128: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001831 (mapset S001833) at src/R0011831.pli:197: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001831 (mapset S001833) at src/R0011831.pli:200: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001831 (mapset S001833) at src/R0011831.pli:342: no single BMS source defines it (candidates: none in the repository)
 * TODO: RECEIVE MAP S001831 (mapset S001833) at src/R0011831.pli:345: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001831 (mapset S001833) at src/R0011831.pli:368: no single BMS source defines it (candidates: none in the repository)
 * TODO: SEND MAP S001831 (mapset S001833) at src/R0011831.pli:372: no single BMS source defines it (candidates: none in the repository)
 */
@Service
@Transactional
@RequiredArgsConstructor
public class SrcR0011831Service {

    private static final Logger log = LoggerFactory.getLogger(SrcR0011831Service.class);

    private final ObjectProvider<SrcR0010301Service> srcR0010301Service;
    private final ObjectProvider<SrcR0010401Service> srcR0010401Service;

    public void executeSrcR0011831(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for src__R0011831");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public void handleLink() {
        log.info("SrcR0011831: handleLink");
    }

    /** EXEC CICS XCTL PROGRAM(R0010301) at src/R0011831.pli:139. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcR0010301() {
        srcR0010301Service.getObject().handleLink();
    }

    /** EXEC CICS XCTL PROGRAM(R0010401) at src/R0011831.pli:149, src/R0011831.pli:311. XCTL transfers control: nothing after it runs in the caller.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public void xctlSrcR0010401() {
        srcR0010401Service.getObject().handleLink();
    }

    /**
     * EXEC CICS SYNCPOINT ROLLBACK at src/R0011831.pli:349 (paragraph UTGANG): rolls the unit of work back.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void rollbackL349() {
        throw new UnitOfWorkRollbackException("SRC__R0011831", "src/R0011831.pli:349");
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/R0011831.pli:101 (paragraph R00118) routes ERROR to FEILBEH.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL101(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL FEILBEH at line 101", e);
        // TODO: port paragraph FEILBEH's logic
    }

    /**
     * EXEC CICS HANDLE CONDITION at src/R0011831.pli:318 (paragraph UTGANG) routes ERROR to ABEND.
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     */
    public void onConditionErrorL318(CicsConditionException e) {
        log.info("HANDLE CONDITION ERROR LABEL ABEND at line 318", e);
        // TODO: port paragraph ABEND's logic
    }

    /**
     * EXEC CICS ABEND ABCODE(FEIL) at src/R0011831.pli:359 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendFeilL359() {
        throw new CicsAbendException("FEIL", "SRC__R0011831", "src/R0011831.pli:359");
    }

}