/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto.screen;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BMS map CCRDUPA of mapset COCRDUP (app/bms/COCRDUP.bms): the screen as a view model (#3619).
 * SEND at app/cbl/COCRDUPC.cbl:1329; RECEIVE at app/cbl/COCRDUPC.cbl:579.
 * One property per named field (symbolic map CCRDUPAI / CCRDUPAO); LAYOUT is every field in
 * screen order, labels included. BMS screen fields field testing: open (3 public / 0 private estates).
 */
@Data
@NoArgsConstructor
public class CcrdupaScreen implements ScreenModel {

    public static final String MAPSET = "COCRDUP";
    public static final String MAP = "CCRDUPA";
    public static final List<ScreenField> LAYOUT = List.of(
            new ScreenField(null, 1, 1, 5, false, false, false, false, false, "Tran:", "BLUE", 1),
            new ScreenField("TRNNAME", 1, 7, 4, false, false, false, false, false, null, "BLUE", 1),
            new ScreenField("TITLE01", 1, 21, 40, false, false, false, false, false, null, "YELLOW", 1),
            new ScreenField(null, 1, 65, 5, false, false, false, false, false, "Date:", "BLUE", 1),
            new ScreenField("CURDATE", 1, 71, 8, false, false, false, false, false, "mm/dd/yy", "BLUE", 1),
            new ScreenField(null, 2, 1, 5, false, false, false, false, false, "Prog:", "BLUE", 1),
            new ScreenField("PGMNAME", 2, 7, 8, false, false, false, false, false, null, "BLUE", 1),
            new ScreenField("TITLE02", 2, 21, 40, false, false, false, false, false, null, "YELLOW", 1),
            new ScreenField(null, 2, 65, 5, false, false, false, false, false, "Time:", "BLUE", 1),
            new ScreenField("CURTIME", 2, 71, 8, false, false, false, false, false, "hh:mm:ss", "BLUE", 1),
            new ScreenField(null, 4, 30, 26, false, false, false, false, false, "Update Credit Card Details", "NEUTRAL", 1),
            new ScreenField(null, 7, 23, 19, false, false, false, false, false, "Account Number    :", "TURQUOISE", 1),
            new ScreenField("ACCTSID", 7, 45, 11, false, false, false, false, true, null, "DEFAULT", 1),
            new ScreenField(null, 7, 57, 0, false, false, false, false, false, null, null, 1),
            new ScreenField(null, 8, 23, 19, false, false, false, false, false, "Card Number       :", "TURQUOISE", 1),
            new ScreenField("CARDSID", 8, 45, 16, true, false, false, false, false, null, "DEFAULT", 1),
            new ScreenField(null, 8, 62, 0, false, false, false, false, false, null, null, 1),
            new ScreenField(null, 11, 4, 20, false, false, false, false, false, "Name on card      :", "TURQUOISE", 1),
            new ScreenField("CRDNAME", 11, 25, 50, true, false, false, false, false, null, null, 1),
            new ScreenField(null, 11, 76, 0, false, false, false, false, false, null, null, 1),
            new ScreenField(null, 13, 4, 20, false, false, false, false, false, "Card Active Y/N   : ", "TURQUOISE", 1),
            new ScreenField("CRDSTCD", 13, 25, 1, true, false, false, false, false, null, null, 1),
            new ScreenField(null, 13, 27, 0, false, false, false, false, false, null, null, 1),
            new ScreenField(null, 15, 4, 20, false, false, false, false, false, "Expiry Date       : ", "TURQUOISE", 1),
            new ScreenField("EXPMON", 15, 25, 2, true, false, false, false, false, null, null, 1),
            new ScreenField(null, 15, 28, 1, false, false, false, false, false, "/", null, 1),
            new ScreenField("EXPYEAR", 15, 30, 4, true, false, false, false, false, null, null, 1),
            new ScreenField(null, 15, 35, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("EXPDAY", 15, 36, 2, false, false, false, true, false, null, null, 1),
            new ScreenField(null, 15, 39, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("INFOMSG", 20, 25, 40, false, false, false, false, false, null, "NEUTRAL", 1),
            new ScreenField("ERRMSG", 23, 1, 80, false, false, true, false, false, null, "RED", 1),
            new ScreenField("FKEYS", 24, 1, 21, false, false, false, false, false, "ENTER=Process F3=Exit", "YELLOW", 1),
            new ScreenField("FKEYSC", 24, 23, 18, false, false, false, true, false, "F5=Save F12=Cancel", "YELLOW", 1));

    /** TRNNAME: (1,7), 4 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COCRDUP.bms:34. Symbolic map TRNNAMEI, TRNNAMEO. */
    private String trnname;

    /** TITLE01: (1,21), 40 bytes, ATTRB=ASKIP,NORM -- app/bms/COCRDUP.bms:38. Symbolic map TITLE01I, TITLE01O. */
    private String title01;

    /** CURDATE: (1,71), 8 bytes, ATTRB=ASKIP,NORM -- app/bms/COCRDUP.bms:47. Symbolic map CURDATEI, CURDATEO. */
    private String curdate;

    /** PGMNAME: (2,7), 8 bytes, ATTRB=ASKIP,NORM -- app/bms/COCRDUP.bms:57. Symbolic map PGMNAMEI, PGMNAMEO. */
    private String pgmname;

    /** TITLE02: (2,21), 40 bytes, ATTRB=ASKIP,NORM -- app/bms/COCRDUP.bms:61. Symbolic map TITLE02I, TITLE02O. */
    private String title02;

    /** CURTIME: (2,71), 8 bytes, ATTRB=ASKIP,NORM -- app/bms/COCRDUP.bms:70. Symbolic map CURTIMEI, CURTIMEO. */
    private String curtime;

    /** ACCTSID: (7,45), 11 bytes, ATTRB=FSET,IC,NORM,PROT -- app/bms/COCRDUP.bms:84. Symbolic map ACCTSIDI, ACCTSIDO. */
    private String acctsid;

    /** CARDSID: (8,45), 16 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COCRDUP.bms:96. Symbolic map CARDSIDI, CARDSIDO. */
    private String cardsid;

    /** CRDNAME: (11,25), 50 bytes, ATTRB=UNPROT -- app/bms/COCRDUP.bms:107. Symbolic map CRDNAMEI, CRDNAMEO. */
    private String crdname;

    /** CRDSTCD: (13,25), 1 bytes, ATTRB=UNPROT -- app/bms/COCRDUP.bms:117. Symbolic map CRDSTCDI, CRDSTCDO. */
    private String crdstcd;

    /** EXPMON: (15,25), 2 bytes, ATTRB=UNPROT -- app/bms/COCRDUP.bms:127. Symbolic map EXPMONI, EXPMONO. */
    private String expmon;

    /** EXPYEAR: (15,30), 4 bytes, ATTRB=UNPROT -- app/bms/COCRDUP.bms:135. Symbolic map EXPYEARI, EXPYEARO. */
    private String expyear;

    /** EXPDAY: (15,36), 2 bytes, ATTRB=DRK,FSET,PROT -- app/bms/COCRDUP.bms:142. Symbolic map EXPDAYI, EXPDAYO. */
    private String expday;

    /** INFOMSG: (20,25), 40 bytes, ATTRB=PROT -- app/bms/COCRDUP.bms:149. Symbolic map INFOMSGI, INFOMSGO. */
    private String infomsg;

    /** ERRMSG: (23,1), 80 bytes, ATTRB=ASKIP,BRT,FSET -- app/bms/COCRDUP.bms:154. Symbolic map ERRMSGI, ERRMSGO. */
    private String errmsg;

    /** FKEYS: (24,1), 21 bytes, ATTRB=ASKIP,NORM -- app/bms/COCRDUP.bms:158. Symbolic map FKEYSI, FKEYSO. */
    private String fkeys;

    /** FKEYSC: (24,23), 18 bytes, ATTRB=ASKIP,DRK -- app/bms/COCRDUP.bms:163. Symbolic map FKEYSCI, FKEYSCO. */
    private String fkeysc;

    @Override
    public String mapsetName() {
        return MAPSET;
    }

    @Override
    public String mapName() {
        return MAP;
    }

    @Override
    public List<ScreenField> screenLayout() {
        return LAYOUT;
    }

    @Override
    public Map<String, String> screenValues() {
        Map<String, String> values = new LinkedHashMap<>();
        values.put("TRNNAME", trnname);
        values.put("TITLE01", title01);
        values.put("CURDATE", curdate);
        values.put("PGMNAME", pgmname);
        values.put("TITLE02", title02);
        values.put("CURTIME", curtime);
        values.put("ACCTSID", acctsid);
        values.put("CARDSID", cardsid);
        values.put("CRDNAME", crdname);
        values.put("CRDSTCD", crdstcd);
        values.put("EXPMON", expmon);
        values.put("EXPYEAR", expyear);
        values.put("EXPDAY", expday);
        values.put("INFOMSG", infomsg);
        values.put("ERRMSG", errmsg);
        values.put("FKEYS", fkeys);
        values.put("FKEYSC", fkeysc);
        return values;
    }

    /** A view model from posted form values (keys as `screenValues` writes them). */
    public static CcrdupaScreen fromValues(Map<String, String> values) {
        CcrdupaScreen screen = new CcrdupaScreen();
        screen.setTrnname(values.get("TRNNAME"));
        screen.setTitle01(values.get("TITLE01"));
        screen.setCurdate(values.get("CURDATE"));
        screen.setPgmname(values.get("PGMNAME"));
        screen.setTitle02(values.get("TITLE02"));
        screen.setCurtime(values.get("CURTIME"));
        screen.setAcctsid(values.get("ACCTSID"));
        screen.setCardsid(values.get("CARDSID"));
        screen.setCrdname(values.get("CRDNAME"));
        screen.setCrdstcd(values.get("CRDSTCD"));
        screen.setExpmon(values.get("EXPMON"));
        screen.setExpyear(values.get("EXPYEAR"));
        screen.setExpday(values.get("EXPDAY"));
        screen.setInfomsg(values.get("INFOMSG"));
        screen.setErrmsg(values.get("ERRMSG"));
        screen.setFkeys(values.get("FKEYS"));
        screen.setFkeysc(values.get("FKEYSC"));
        return screen;
    }
}
