/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto.screen;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BMS map COTRN0A of mapset COTRN00 (app/bms/COTRN00.bms): the screen as a view model (#3619).
 * SEND at app/cbl/COTRN00C.cbl:534, app/cbl/COTRN00C.cbl:542; RECEIVE at app/cbl/COTRN00C.cbl:556.
 * One property per named field (symbolic map COTRN0AI / COTRN0AO); LAYOUT is every field in
 * screen order, labels included. BMS screen fields field testing: open (3 public / 0 private estates).
 */
@Data
@NoArgsConstructor
public class Cotrn0aScreen implements ScreenModel {

    public static final String MAPSET = "COTRN00";
    public static final String MAP = "COTRN0A";
    public static final List<ScreenField> LAYOUT = List.of(
            new ScreenField(null, 1, 1, 5, false, false, false, false, false, "Tran:", "BLUE", 1),
            new ScreenField("TRNNAME", 1, 7, 4, false, false, false, false, false, null, "BLUE", 1),
            new ScreenField("TITLE01", 1, 21, 40, false, false, false, false, false, null, "YELLOW", 1),
            new ScreenField(null, 1, 65, 5, false, false, false, false, false, "Date:", "BLUE", 1),
            new ScreenField("CURDATE", 1, 71, 8, false, false, false, false, false, "mm/dd/yy", "BLUE", 1),
            new ScreenField(null, 2, 1, 5, false, false, false, false, false, "Prog:", "BLUE", 1),
            new ScreenField("PGMNAME", 2, 7, 8, false, false, false, false, false, null, "BLUE", 1),
            new ScreenField("TITLE02", 2, 21, 40, false, false, false, false, false, null, "YELLOW", 1),
            new ScreenField(null, 2, 65, 5, false, false, false, false, false, "Time:", "BLUE", 1),
            new ScreenField("CURTIME", 2, 71, 8, false, false, false, false, false, "hh:mm:ss", "BLUE", 1),
            new ScreenField(null, 4, 30, 17, false, false, true, false, false, "List Transactions", "NEUTRAL", 1),
            new ScreenField(null, 4, 65, 5, false, false, true, false, false, "Page:", "TURQUOISE", 1),
            new ScreenField("PAGENUM", 4, 71, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField(null, 6, 5, 15, false, false, false, false, false, "Search Tran ID:", "TURQUOISE", 1),
            new ScreenField("TRNIDIN", 6, 21, 16, true, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 6, 38, 0, false, false, false, false, false, null, null, 1),
            new ScreenField(null, 8, 2, 3, false, false, false, false, false, "Sel", "NEUTRAL", 1),
            new ScreenField(null, 8, 8, 16, false, false, false, false, false, " Transaction ID ", "NEUTRAL", 1),
            new ScreenField(null, 8, 27, 8, false, false, false, false, false, "  Date  ", "NEUTRAL", 1),
            new ScreenField(null, 8, 38, 26, false, false, false, false, false, "     Description          ", "NEUTRAL", 1),
            new ScreenField(null, 8, 67, 12, false, false, false, false, false, "   Amount   ", "NEUTRAL", 1),
            new ScreenField(null, 9, 2, 3, false, false, false, false, false, "---", "NEUTRAL", 1),
            new ScreenField(null, 9, 8, 16, false, false, false, false, false, "----------------", "NEUTRAL", 1),
            new ScreenField(null, 9, 27, 8, false, false, false, false, false, "--------", "NEUTRAL", 1),
            new ScreenField(null, 9, 38, 26, false, false, false, false, false, "--------------------------", "NEUTRAL", 1),
            new ScreenField(null, 9, 67, 12, false, false, false, false, false, "------------", "NEUTRAL", 1),
            new ScreenField("SEL0001", 10, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 10, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID01", 10, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE01", 10, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC01", 10, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT001", 10, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0002", 11, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 11, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID02", 11, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE02", 11, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC02", 11, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT002", 11, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0003", 12, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 12, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID03", 12, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE03", 12, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC03", 12, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT003", 12, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0004", 13, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 13, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID04", 13, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE04", 13, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC04", 13, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT004", 13, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0005", 14, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 14, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID05", 14, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE05", 14, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC05", 14, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT005", 14, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0006", 15, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 15, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID06", 15, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE06", 15, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC06", 15, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT006", 15, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0007", 16, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 16, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID07", 16, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE07", 16, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC07", 16, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT007", 16, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0008", 17, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 17, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID08", 17, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE08", 17, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC08", 17, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT008", 17, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0009", 18, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 18, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID09", 18, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE09", 18, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC09", 18, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT009", 18, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("SEL0010", 19, 3, 1, true, false, false, false, false, " ", "GREEN", 1),
            new ScreenField(null, 19, 5, 0, false, false, false, false, false, null, null, 1),
            new ScreenField("TRNID10", 19, 8, 16, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDATE10", 19, 27, 8, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TDESC10", 19, 38, 26, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField("TAMT010", 19, 67, 12, false, false, false, false, false, " ", "BLUE", 1),
            new ScreenField(null, 21, 12, 50, false, false, true, false, false, "Type 'S' to View Transaction details from the list", "NEUTRAL", 1),
            new ScreenField("ERRMSG", 23, 1, 78, false, false, true, false, false, null, "RED", 1),
            new ScreenField(null, 24, 1, 48, false, false, false, false, false, "ENTER=Continue  F3=Back  F7=Backward  F8=Forward", "YELLOW", 1));

    /** TRNNAME: (1,7), 4 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:34. Symbolic map TRNNAMEI, TRNNAMEO. */
    private String trnname;

    /** TITLE01: (1,21), 40 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:38. Symbolic map TITLE01I, TITLE01O. */
    private String title01;

    /** CURDATE: (1,71), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:47. Symbolic map CURDATEI, CURDATEO. */
    private String curdate;

    /** PGMNAME: (2,7), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:57. Symbolic map PGMNAMEI, PGMNAMEO. */
    private String pgmname;

    /** TITLE02: (2,21), 40 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:61. Symbolic map TITLE02I, TITLE02O. */
    private String title02;

    /** CURTIME: (2,71), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:70. Symbolic map CURTIMEI, CURTIMEO. */
    private String curtime;

    /** PAGENUM: (4,71), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:85. Symbolic map PAGENUMI, PAGENUMO. */
    private String pagenum;

    /** TRNIDIN: (6,21), 16 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:95. Symbolic map TRNIDINI, TRNIDINO. */
    private String trnidin;

    /** SEL0001: (10,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:153. Symbolic map SEL0001I, SEL0001O. */
    private String sel0001;

    /** TRNID01: (10,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:162. Symbolic map TRNID01I, TRNID01O. */
    private String trnid01;

    /** TDATE01: (10,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:167. Symbolic map TDATE01I, TDATE01O. */
    private String tdate01;

    /** TDESC01: (10,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:172. Symbolic map TDESC01I, TDESC01O. */
    private String tdesc01;

    /** TAMT001: (10,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:177. Symbolic map TAMT001I, TAMT001O. */
    private String tamt001;

    /** SEL0002: (11,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:182. Symbolic map SEL0002I, SEL0002O. */
    private String sel0002;

    /** TRNID02: (11,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:191. Symbolic map TRNID02I, TRNID02O. */
    private String trnid02;

    /** TDATE02: (11,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:196. Symbolic map TDATE02I, TDATE02O. */
    private String tdate02;

    /** TDESC02: (11,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:201. Symbolic map TDESC02I, TDESC02O. */
    private String tdesc02;

    /** TAMT002: (11,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:206. Symbolic map TAMT002I, TAMT002O. */
    private String tamt002;

    /** SEL0003: (12,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:211. Symbolic map SEL0003I, SEL0003O. */
    private String sel0003;

    /** TRNID03: (12,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:220. Symbolic map TRNID03I, TRNID03O. */
    private String trnid03;

    /** TDATE03: (12,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:225. Symbolic map TDATE03I, TDATE03O. */
    private String tdate03;

    /** TDESC03: (12,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:230. Symbolic map TDESC03I, TDESC03O. */
    private String tdesc03;

    /** TAMT003: (12,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:235. Symbolic map TAMT003I, TAMT003O. */
    private String tamt003;

    /** SEL0004: (13,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:240. Symbolic map SEL0004I, SEL0004O. */
    private String sel0004;

    /** TRNID04: (13,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:249. Symbolic map TRNID04I, TRNID04O. */
    private String trnid04;

    /** TDATE04: (13,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:254. Symbolic map TDATE04I, TDATE04O. */
    private String tdate04;

    /** TDESC04: (13,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:259. Symbolic map TDESC04I, TDESC04O. */
    private String tdesc04;

    /** TAMT004: (13,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:264. Symbolic map TAMT004I, TAMT004O. */
    private String tamt004;

    /** SEL0005: (14,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:269. Symbolic map SEL0005I, SEL0005O. */
    private String sel0005;

    /** TRNID05: (14,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:278. Symbolic map TRNID05I, TRNID05O. */
    private String trnid05;

    /** TDATE05: (14,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:283. Symbolic map TDATE05I, TDATE05O. */
    private String tdate05;

    /** TDESC05: (14,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:288. Symbolic map TDESC05I, TDESC05O. */
    private String tdesc05;

    /** TAMT005: (14,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:293. Symbolic map TAMT005I, TAMT005O. */
    private String tamt005;

    /** SEL0006: (15,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:298. Symbolic map SEL0006I, SEL0006O. */
    private String sel0006;

    /** TRNID06: (15,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:307. Symbolic map TRNID06I, TRNID06O. */
    private String trnid06;

    /** TDATE06: (15,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:312. Symbolic map TDATE06I, TDATE06O. */
    private String tdate06;

    /** TDESC06: (15,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:317. Symbolic map TDESC06I, TDESC06O. */
    private String tdesc06;

    /** TAMT006: (15,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:322. Symbolic map TAMT006I, TAMT006O. */
    private String tamt006;

    /** SEL0007: (16,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:327. Symbolic map SEL0007I, SEL0007O. */
    private String sel0007;

    /** TRNID07: (16,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:336. Symbolic map TRNID07I, TRNID07O. */
    private String trnid07;

    /** TDATE07: (16,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:341. Symbolic map TDATE07I, TDATE07O. */
    private String tdate07;

    /** TDESC07: (16,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:346. Symbolic map TDESC07I, TDESC07O. */
    private String tdesc07;

    /** TAMT007: (16,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:351. Symbolic map TAMT007I, TAMT007O. */
    private String tamt007;

    /** SEL0008: (17,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:356. Symbolic map SEL0008I, SEL0008O. */
    private String sel0008;

    /** TRNID08: (17,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:365. Symbolic map TRNID08I, TRNID08O. */
    private String trnid08;

    /** TDATE08: (17,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:370. Symbolic map TDATE08I, TDATE08O. */
    private String tdate08;

    /** TDESC08: (17,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:375. Symbolic map TDESC08I, TDESC08O. */
    private String tdesc08;

    /** TAMT008: (17,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:380. Symbolic map TAMT008I, TAMT008O. */
    private String tamt008;

    /** SEL0009: (18,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:385. Symbolic map SEL0009I, SEL0009O. */
    private String sel0009;

    /** TRNID09: (18,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:394. Symbolic map TRNID09I, TRNID09O. */
    private String trnid09;

    /** TDATE09: (18,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:399. Symbolic map TDATE09I, TDATE09O. */
    private String tdate09;

    /** TDESC09: (18,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:404. Symbolic map TDESC09I, TDESC09O. */
    private String tdesc09;

    /** TAMT009: (18,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:409. Symbolic map TAMT009I, TAMT009O. */
    private String tamt009;

    /** SEL0010: (19,3), 1 bytes, ATTRB=FSET,NORM,UNPROT -- app/bms/COTRN00.bms:414. Symbolic map SEL0010I, SEL0010O. */
    private String sel0010;

    /** TRNID10: (19,8), 16 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:423. Symbolic map TRNID10I, TRNID10O. */
    private String trnid10;

    /** TDATE10: (19,27), 8 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:428. Symbolic map TDATE10I, TDATE10O. */
    private String tdate10;

    /** TDESC10: (19,38), 26 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:433. Symbolic map TDESC10I, TDESC10O. */
    private String tdesc10;

    /** TAMT010: (19,67), 12 bytes, ATTRB=ASKIP,FSET,NORM -- app/bms/COTRN00.bms:438. Symbolic map TAMT010I, TAMT010O. */
    private String tamt010;

    /** ERRMSG: (23,1), 78 bytes, ATTRB=ASKIP,BRT,FSET -- app/bms/COTRN00.bms:450. Symbolic map ERRMSGI, ERRMSGO. */
    private String errmsg;

    @Override
    public String mapsetName() {
        return MAPSET;
    }

    @Override
    public String mapName() {
        return MAP;
    }

    @Override
    public List<ScreenField> screenLayout() {
        return LAYOUT;
    }

    @Override
    public Map<String, String> screenValues() {
        Map<String, String> values = new LinkedHashMap<>();
        values.put("TRNNAME", trnname);
        values.put("TITLE01", title01);
        values.put("CURDATE", curdate);
        values.put("PGMNAME", pgmname);
        values.put("TITLE02", title02);
        values.put("CURTIME", curtime);
        values.put("PAGENUM", pagenum);
        values.put("TRNIDIN", trnidin);
        values.put("SEL0001", sel0001);
        values.put("TRNID01", trnid01);
        values.put("TDATE01", tdate01);
        values.put("TDESC01", tdesc01);
        values.put("TAMT001", tamt001);
        values.put("SEL0002", sel0002);
        values.put("TRNID02", trnid02);
        values.put("TDATE02", tdate02);
        values.put("TDESC02", tdesc02);
        values.put("TAMT002", tamt002);
        values.put("SEL0003", sel0003);
        values.put("TRNID03", trnid03);
        values.put("TDATE03", tdate03);
        values.put("TDESC03", tdesc03);
        values.put("TAMT003", tamt003);
        values.put("SEL0004", sel0004);
        values.put("TRNID04", trnid04);
        values.put("TDATE04", tdate04);
        values.put("TDESC04", tdesc04);
        values.put("TAMT004", tamt004);
        values.put("SEL0005", sel0005);
        values.put("TRNID05", trnid05);
        values.put("TDATE05", tdate05);
        values.put("TDESC05", tdesc05);
        values.put("TAMT005", tamt005);
        values.put("SEL0006", sel0006);
        values.put("TRNID06", trnid06);
        values.put("TDATE06", tdate06);
        values.put("TDESC06", tdesc06);
        values.put("TAMT006", tamt006);
        values.put("SEL0007", sel0007);
        values.put("TRNID07", trnid07);
        values.put("TDATE07", tdate07);
        values.put("TDESC07", tdesc07);
        values.put("TAMT007", tamt007);
        values.put("SEL0008", sel0008);
        values.put("TRNID08", trnid08);
        values.put("TDATE08", tdate08);
        values.put("TDESC08", tdesc08);
        values.put("TAMT008", tamt008);
        values.put("SEL0009", sel0009);
        values.put("TRNID09", trnid09);
        values.put("TDATE09", tdate09);
        values.put("TDESC09", tdesc09);
        values.put("TAMT009", tamt009);
        values.put("SEL0010", sel0010);
        values.put("TRNID10", trnid10);
        values.put("TDATE10", tdate10);
        values.put("TDESC10", tdesc10);
        values.put("TAMT010", tamt010);
        values.put("ERRMSG", errmsg);
        return values;
    }

    /** A view model from posted form values (keys as `screenValues` writes them). */
    public static Cotrn0aScreen fromValues(Map<String, String> values) {
        Cotrn0aScreen screen = new Cotrn0aScreen();
        screen.setTrnname(values.get("TRNNAME"));
        screen.setTitle01(values.get("TITLE01"));
        screen.setCurdate(values.get("CURDATE"));
        screen.setPgmname(values.get("PGMNAME"));
        screen.setTitle02(values.get("TITLE02"));
        screen.setCurtime(values.get("CURTIME"));
        screen.setPagenum(values.get("PAGENUM"));
        screen.setTrnidin(values.get("TRNIDIN"));
        screen.setSel0001(values.get("SEL0001"));
        screen.setTrnid01(values.get("TRNID01"));
        screen.setTdate01(values.get("TDATE01"));
        screen.setTdesc01(values.get("TDESC01"));
        screen.setTamt001(values.get("TAMT001"));
        screen.setSel0002(values.get("SEL0002"));
        screen.setTrnid02(values.get("TRNID02"));
        screen.setTdate02(values.get("TDATE02"));
        screen.setTdesc02(values.get("TDESC02"));
        screen.setTamt002(values.get("TAMT002"));
        screen.setSel0003(values.get("SEL0003"));
        screen.setTrnid03(values.get("TRNID03"));
        screen.setTdate03(values.get("TDATE03"));
        screen.setTdesc03(values.get("TDESC03"));
        screen.setTamt003(values.get("TAMT003"));
        screen.setSel0004(values.get("SEL0004"));
        screen.setTrnid04(values.get("TRNID04"));
        screen.setTdate04(values.get("TDATE04"));
        screen.setTdesc04(values.get("TDESC04"));
        screen.setTamt004(values.get("TAMT004"));
        screen.setSel0005(values.get("SEL0005"));
        screen.setTrnid05(values.get("TRNID05"));
        screen.setTdate05(values.get("TDATE05"));
        screen.setTdesc05(values.get("TDESC05"));
        screen.setTamt005(values.get("TAMT005"));
        screen.setSel0006(values.get("SEL0006"));
        screen.setTrnid06(values.get("TRNID06"));
        screen.setTdate06(values.get("TDATE06"));
        screen.setTdesc06(values.get("TDESC06"));
        screen.setTamt006(values.get("TAMT006"));
        screen.setSel0007(values.get("SEL0007"));
        screen.setTrnid07(values.get("TRNID07"));
        screen.setTdate07(values.get("TDATE07"));
        screen.setTdesc07(values.get("TDESC07"));
        screen.setTamt007(values.get("TAMT007"));
        screen.setSel0008(values.get("SEL0008"));
        screen.setTrnid08(values.get("TRNID08"));
        screen.setTdate08(values.get("TDATE08"));
        screen.setTdesc08(values.get("TDESC08"));
        screen.setTamt008(values.get("TAMT008"));
        screen.setSel0009(values.get("SEL0009"));
        screen.setTrnid09(values.get("TRNID09"));
        screen.setTdate09(values.get("TDATE09"));
        screen.setTdesc09(values.get("TDESC09"));
        screen.setTamt009(values.get("TAMT009"));
        screen.setSel0010(values.get("SEL0010"));
        screen.setTrnid10(values.get("TRNID10"));
        screen.setTdate10(values.get("TDATE10"));
        screen.setTdesc10(values.get("TDESC10"));
        screen.setTamt010(values.get("TAMT010"));
        screen.setErrmsg(values.get("ERRMSG"));
        return screen;
    }
}
