/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto.screen;

/**
 * One BMS field (DFHMDF) of a map: where it sits on the 3270 screen and how it behaves (#3619).
 * `name` is null for a screen literal (a label, which never reaches the symbolic map); `line` / `column`
 * are POS=(line,column) -- the attribute byte, so the data starts one column after it; `input` is
 * ATTRB=UNPROT, `numeric` ATTRB=NUM, `bright` BRT, `dark` DRK, `cursor` IC; `initial` the INITIAL text;
 * `occurs` the OCCURS count (1 without one).
 */
public record ScreenField(String name, int line, int column, int length, boolean input, boolean numeric,
                          boolean bright, boolean dark, boolean cursor, String initial, String color, int occurs) {
}
