/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import lombok.RequiredArgsConstructor;
import com.gitgalaxy.modernized.dto.contract.Copaua0cDfhcommarea;
import com.gitgalaxy.modernized.service.Copaua0cService;

/**
 * CICS program COPAUA0C (app/app-authorization-ims-db2-mq/cbl/COPAUA0C.cbl), generated from GitGalaxy's
 * verified skeleton (06_skeleton). Each endpoint names the fact it came from.
 * COMMAREA: DFHCOMMAREA (app/app-authorization-ims-db2-mq/cbl/COPAUA0C.cbl, 4096 bytes) -> Copaua0cDfhcommarea.
 * Field testing: entry transactions open (4 public / 0 private estates);
 * record fields field-tested (6 public / 0 private estates).
 */
@RestController
@RequestMapping("/api/v1/copaua0c")
@RequiredArgsConstructor
public class Copaua0cController {

    private final Copaua0cService copaua0cService;

    /** CICS transaction CP00 -> Copaua0c (CSD app/app-authorization-ims-db2-mq/csd/CRDDEMO2.csd:11 group CARDDEMO; app/app-authorization-ims-db2-mq/csd/CRDDEMO2.csd:59 group CARDDEMO). */
    @PostMapping("/transactions/CP00")
    public ResponseEntity<Copaua0cDfhcommarea> transactionCP00(@RequestBody Copaua0cDfhcommarea request) {
        return ResponseEntity.ok(copaua0cService.handleTransaction("CP00", request));
    }

}