/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import lombok.RequiredArgsConstructor;
import com.gitgalaxy.modernized.dto.contract.CarddemoCommarea6;
import com.gitgalaxy.modernized.service.Cousr00cService;

/**
 * CICS program COUSR00C (app/cbl/COUSR00C.cbl), generated from GitGalaxy's
 * verified skeleton (06_skeleton). Each endpoint names the fact it came from.
 * COMMAREA: DFHCOMMAREA (app/cbl/COUSR00C.cbl, 194 bytes) -> CarddemoCommarea6.
 * TODO: callers also pass CARDDEMO-COMMAREA (app/cpy/COCOM01Y.cpy, 194 bytes) at app/cbl/COUSR00C.cbl:141.
 * Field testing: entry transactions open (4 public / 0 private estates);
 * record fields field-tested (6 public / 0 private estates).
 */
@RestController
@RequestMapping("/api/v1/cousr00c")
@RequiredArgsConstructor
public class Cousr00cController {

    private final Cousr00cService cousr00cService;

    /** CICS transaction CU00 -> Cousr00c (CSD app/csd/CARDDEMO.CSD:449 group CARDDEMO). */
    @PostMapping("/transactions/CU00")
    public ResponseEntity<CarddemoCommarea6> transactionCU00(@RequestBody CarddemoCommarea6 request) {
        return ResponseEntity.ok(cousr00cService.handleTransaction("CU00", request));
    }

    /** Program-to-program entry: XCTL at app/cbl/COADM01C.cbl:145 (data-driven, table). */
    @PostMapping("/link")
    public ResponseEntity<CarddemoCommarea6> link(@RequestBody CarddemoCommarea6 request) {
        return ResponseEntity.ok(cousr00cService.handleLink(request));
    }

}