/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import lombok.RequiredArgsConstructor;
import com.gitgalaxy.modernized.dto.contract.Crdtagy2ChannelIn;
import com.gitgalaxy.modernized.dto.contract.Crdtagy2ChannelOut;
import com.gitgalaxy.modernized.service.Crdtagy2Service;

/**
 * CICS program CRDTAGY2 (src/base/cobol_src/CRDTAGY2.cbl), generated from GitGalaxy's
 * verified skeleton (06_skeleton). Each endpoint names the fact it came from.
 * No COMMAREA: the program exchanges its data through its channel's containers.
 * Field testing: entry transactions open (4 public / 0 private estates);
 * record fields field-tested (6 public / 0 private estates).
 */
@RestController
@RequestMapping("/api/v1/crdtagy2")
@RequiredArgsConstructor
public class Crdtagy2Controller {

    private final Crdtagy2Service crdtagy2Service;

    /** CICS transaction OCR2 -> Crdtagy2 (CSD etc/install/base/installjcl/BANK.csd:355 group BANK). */
    @PostMapping("/transactions/OCR2")
    public ResponseEntity<Crdtagy2ChannelOut> transactionOCR2(@RequestBody Crdtagy2ChannelIn request) {
        return ResponseEntity.ok(crdtagy2Service.handleTransaction("OCR2", request));
    }

}