/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import lombok.RequiredArgsConstructor;
import com.gitgalaxy.modernized.service.Fo04f1x1Service;

import org.springframework.web.multipart.MultipartFile;
import org.springframework.http.MediaType;

@RestController
@RequestMapping("/api/v1/fo04f1x1")
@RequiredArgsConstructor
public class Fo04f1x1Controller {

    private final Fo04f1x1Service fo04f1x1Service;

    @PostMapping(value = "/execute-batch", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<?> executeFo04f1x1Batch(
        @RequestParam("sys006File") MultipartFile sys006File,
        @RequestParam("sys005File") MultipartFile sys005File,
        @RequestParam("sys004File") MultipartFile sys004File
    ) {
        // BATCH PARADIGM DETECTED
        // Pass the InputStream directly to the Service layer.
        fo04f1x1Service.executeFo04f1x1(/* pass streams here */);

        // Expected Outputs: SYS005
        return ResponseEntity.ok().build();
    }
}