/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import lombok.RequiredArgsConstructor;
import com.gitgalaxy.modernized.service.R0017203Service;


@RestController
@RequestMapping("/api/v1/r0017203")
@RequiredArgsConstructor
public class R0017203Controller {

    private final R0017203Service r0017203Service;

    @PostMapping("/execute")
    public ResponseEntity<?> executeR0017203(
        /* No external data dependencies detected */
    ) {
        // TRANSACTIONAL PARADIGM DETECTED
        r0017203Service.executeR0017203(/* pass DTOs here */);

        return ResponseEntity.noContent().build();
    }
}