/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import lombok.RequiredArgsConstructor;
import com.gitgalaxy.modernized.service.SrcGmlR001tk70Service;

/**
 * CICS program R001TK70 (src/GML/R001TK70.pli), generated from GitGalaxy's
 * verified skeleton (06_skeleton). Each endpoint names the fact it came from.
 * TODO: no COMMAREA layout: no structure parameter, or structure BASED on the main procedure's parameter COMMAREA_PEKER, is declared in the program or its %INCLUDE members; %INCLUDE members not in the repository: P0012003, P001TK03, P001TK51, P001TK52, P001TK53, S001T7, S001TK; no resolved caller passes a COMMAREA.
 * Field testing: entry transactions open (4 public / 0 private estates);
 * record fields field-tested (6 public / 0 private estates).
 */
@RestController
@RequestMapping("/api/v1/src-gml-r001tk70")
@RequiredArgsConstructor
public class SrcGmlR001tk70Controller {

    private final SrcGmlR001tk70Service srcGmlR001tk70Service;

    /** Program-to-program entry: no CSD transaction enters this program. */
    @PostMapping("/link")
    public ResponseEntity<Void> link() {
        srcGmlR001tk70Service.handleLink();
        return ResponseEntity.noContent().build();
    }

}