/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/navikt/DSF at commit faade4961e316c89e8c312456bae411c63f1c482,
 * which is licensed MIT. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import lombok.RequiredArgsConstructor;
import com.gitgalaxy.modernized.service.SrcR0016601Service;

/**
 * CICS program R0016601 (src/R0016601.pli), generated from GitGalaxy's
 * verified skeleton (06_skeleton). Each endpoint names the fact it came from.
 * TODO: no COMMAREA layout: no structure parameter, or structure BASED on the main procedure's parameter COMMAREA_PEKER, is declared in the program or its %INCLUDE members; %INCLUDE members not in the repository: P0012002, P0012003, P0016201, P0016202, P0019906, P0019908, P0019912; no resolved caller passes a COMMAREA.
 * Field testing: entry transactions open (4 public / 0 private estates);
 * record fields field-tested (6 public / 0 private estates).
 */
@RestController
@RequestMapping("/api/v1/src-r0016601")
@RequiredArgsConstructor
public class SrcR0016601Controller {

    private final SrcR0016601Service srcR0016601Service;

    /** Program-to-program entry: LINK at src/R0016022.pli:429, LINK at src/R0016022.pli:2187, LINK at src/R0016023.pli:1035. */
    @PostMapping("/link")
    public ResponseEntity<Void> link() {
        srcR0016601Service.handleLink();
        return ResponseEntity.noContent().build();
    }

}