/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-genapp at commit f6f3f4b2580d31b7d8dcc31ce3e3676f4cceaaaa,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
public class Lgucvs01DfhcommareaDto {

    private Integer wsResp;

    private Integer wsResp2;

    private Integer wsCommareaLen;

    private String wsCustomerArea;

    private Integer wsAbstime;

    private String wsTime;

    private String wsDate;

    private String emDate;

    private String emTime;

    private String emCusnum;

    private Integer emResprc;

    private Integer emResp2Rc;

    private String caData;

    private Integer customerRecordSize;

}