/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.entity;

import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
@Entity
@Table(name = "WS_INPUT_REC")
public class CobtupdtWsInputRec {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sys_id")
    private Long sysId;

    @Column(name = "LASTREC")
    private String lastrec;

    @Column(name = "WS_RETURN_MSG")
    private String wsReturnMsg;

    @Column(name = "WS_VAR_SQLCODE")
    private Integer wsVarSqlcode;

    @Column(name = "INPUT_REC_TYPE")
    private String inputRecType;

    @Column(name = "INPUT_REC_NUMBER")
    private String inputRecNumber;

    @Column(name = "INPUT_REC_DESC")
    private String inputRecDesc;

}