/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-genapp at commit f6f3f4b2580d31b7d8dcc31ce3e3676f4cceaaaa,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.controller;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import lombok.RequiredArgsConstructor;
import com.gitgalaxy.modernized.dto.contract.Lgapol01Dfhcommarea;
import com.gitgalaxy.modernized.service.Lgapdb01Service;

/**
 * CICS program LGAPDB01 (base/src/lgapdb01.cbl), generated from GitGalaxy's
 * verified skeleton (06_skeleton). Each endpoint names the fact it came from.
 * COMMAREA: DFHCOMMAREA (base/src/lgapol01.cbl, 32500 bytes) -> Lgapol01Dfhcommarea.
 * Field testing: entry transactions open (4 public / 0 private estates);
 * record fields field-tested (6 public / 0 private estates).
 */
@RestController
@RequestMapping("/api/v1/lgapdb01")
@RequiredArgsConstructor
public class Lgapdb01Controller {

    private final Lgapdb01Service lgapdb01Service;

    /** CICS transaction DSPA -> Lgapdb01 (CSD base/cntl/cdef123.jcl:144 group GENAAORP). */
    @PostMapping("/transactions/DSPA")
    public ResponseEntity<Lgapol01Dfhcommarea> transactionDSPA(@RequestBody Lgapol01Dfhcommarea request) {
        return ResponseEntity.ok(lgapdb01Service.handleTransaction("DSPA", request));
    }

    /** Program-to-program entry: LINK at base/src/lgapol01.cbl:121. */
    @PostMapping("/link")
    public ResponseEntity<Lgapol01Dfhcommarea> link(@RequestBody Lgapol01Dfhcommarea request) {
        return ResponseEntity.ok(lgapdb01Service.handleLink(request));
    }

}