/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
public class AcctctrlDfhcommareaDto {

    private Integer requiredSortCode;

    private Integer sqlcodeDisplay;

    private String wsAccountRangeTop;

    private String wsAccountRangeMiddle;

    private String wsAccountRangeBottom;

    private Integer hvNumberOfAccounts;

    private String hvAccountSortcode;

    private Integer wsUTime;

    private String wsOrigDate;

    private Integer wsTimeNow;

    private Integer wsTimeNowGrpHh;

    private Integer wsTimeNowGrpMm;

    private Integer wsTimeNowGrpSs;

}