/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
public class Bnk1dcsDfhcommareaDto {

    private Integer wsCicsResp;

    private Integer wsCicsResp2;

    private String wsCicsFailMsg;

    private Integer wsCicsRespDisp;

    private Integer wsCicsResp2Disp;

    private String validDataSw;

    private String endOfSessionMessage;

    private Integer wsUctrans;

    private Integer storedUctrans;

    private Integer commDobSplitDd;

    private Integer commDobSplitMm;

    private Integer commDobSplitYyyy;

    private String commAddrSplit1;

    private String commAddrSplit2;

    private String commAddrSplit3;

    private String commDobxDd;

    private String commDobxMm;

    private String commDobxYyyy;

    private Integer commDob9Dd;

    private Integer commDob9Mm;

    private Integer commDob9Yyyy;

    private String commCsReviewxDd;

    private String commCsReviewxMm;

    private String commCsReviewxYyyy;

    private Integer commCsReview9Dd;

    private Integer commCsReview9Mm;

    private Integer commCsReview9Yyyy;

    private String creditScoreX;

    private Integer creditScore9;

    private String commAddrUpd1;

    private String commAddrUpd2;

    private String commAddrUpd3;

    private Integer wsCommTerm;

    private String wsCommEye;

    private String wsCommScode;

    private String wsCommCustno;

    private String wsCommName;

    private String wsCommAddr;

    private Integer wsCommDob;

    private Integer wsCommCreditScore;

    private Integer wsCommCsReviewDate;

    private String wsCommUpdate;

    private String wsValidateName;

    private String wsUnstrTitle;

    private String wsTitleValid;

    private Integer wsUTime;

    private String wsOrigDate;

    private Integer wsTimeNow;

    private Integer wsTimeNowGrpHh;

    private Integer wsTimeNowGrpMm;

    private Integer wsTimeNowGrpSs;

    private String wsAbendPgm;

    private Integer commTerm;

    private String commEye;

    private String commScode;

    private String commCustno;

    private String commName;

    private String commAddr;

    private Integer commDob;

    private Integer commCreditScore;

    private Integer commCsReviewDate;

    private String commDelSuccess;

    private String commDelFailCd;

    private String commUpd;

}