/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
public class DbcrfunDfhcommareaDto {

    private String hvAccountEyecatcher;

    private String hvAccountCustNo;

    private String hvAccountSortcode;

    private String hvAccountAccNo;

    private String hvAccountAccType;

    private BigDecimal hvAccountIntRate;

    private String hvAccountOpened;

    private Integer hvAccountOverdraftLim;

    private String hvAccountLastStmt;

    private String hvAccountNextStmt;

    private BigDecimal hvAccountAvailBal;

    private BigDecimal hvAccountActualBal;

    private String hvProctranEyecatcher;

    private String hvProctranSortCode;

    private String hvProctranAccNumber;

    private String hvProctranDate;

    private String hvProctranTime;

    private String hvProctranRef;

    private String hvProctranType;

    private String hvProctranDesc;

    private BigDecimal hvProctranAmount;

    private Integer wsCicsResp;

    private Integer wsCicsResp2;

    private Integer wsEibtaskn12;

    private Integer desiredSortCode;

    private Integer desiredAccNo;

    private Integer wsUTime;

    private String wsOrigDate;

    private String wsCustomerRangeTop;

    private String wsCustomerRangeMiddle;

    private String wsCustomerRangeBottom;

    private Integer sqlcodeDisplay;

    private String myAbendCode;

    private String wsStormDrain;

    private String stormDrainCondition;

    private Integer wsTimeNow;

    private Integer wsTimeNowGrpHh;

    private Integer wsTimeNowGrpMm;

    private Integer wsTimeNowGrpSs;

    private String wsAbendPgm;

    private BigDecimal wsDifference;

}