/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.dto.contract.Bnk1dacParmsSubpgm;
import com.gitgalaxy.modernized.dto.contract.Bnk1dacWsCommArea;
import com.gitgalaxy.modernized.dto.contract.BnkmenuAbndinfoRec;
import com.gitgalaxy.modernized.dto.contract.InqaccCommarea;
import com.gitgalaxy.modernized.dto.screen.Bnk1daScreen;
import com.gitgalaxy.modernized.dto.screen.ScreenModel;
import com.gitgalaxy.modernized.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

/**
 * Response handling (field testing: field-tested (6 public / 0 private estates)):
 * RETURN at line 295 tests NORMAL
 * RECEIVE at line 426 tests NORMAL
 * LINK at line 553 tests NORMAL
 * LINK at line 712 tests NORMAL
 * SEND at line 827 tests NORMAL
 * SEND at line 906 tests NORMAL
 * SEND at line 980 tests NORMAL
 * SEND at line 1060 tests NORMAL
 * TODO: the RESP of RETURN at line 213 (paragraph A010) is never tested
 * Screens (#3619): Bnk1daScreen.
 */
@Service
@Transactional
@RequiredArgsConstructor
public class Bnk1dacService {

    private static final Logger log = LoggerFactory.getLogger(Bnk1dacService.class);

    private final ObjectProvider<DelaccService> delaccService;
    private final ObjectProvider<InqaccService> inqaccService;
    private final ObjectProvider<AbndprocService> abndprocService;

    public void executeBnk1dac(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for BNK1DAC");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** A CICS transaction entered the program. TODO: [AI AGENT] implement from the program's business rules. */
    public Bnk1dacWsCommArea handleTransaction(String transid, Bnk1dacWsCommArea request) {
        log.info("Bnk1dac: handleTransaction");
        return request;
    }

    /** EXEC CICS LINK PROGRAM(DELACC) at src/base/cobol_src/BNK1DAC.cbl:712.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public Bnk1dacParmsSubpgm linkDelacc(Bnk1dacParmsSubpgm request) {
        return delaccService.getObject().handleLink(request);
    }

    /** EXEC CICS LINK PROGRAM(INQACC) at src/base/cobol_src/BNK1DAC.cbl:553.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public InqaccCommarea linkInqacc(InqaccCommarea request) {
        return inqaccService.getObject().handleLink(request);
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:350: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL350(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:350: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:481: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL481(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:481: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:608: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL608(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:608: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:882: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL882(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:882: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:961: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL961(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:961: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:1036: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL1036(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:1036: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:1115: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL1115(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/BNK1DAC.cbl:1115: no known target " + program);
        }
    }

    /**
     * EXEC CICS ABEND ABCODE(HBNK) at src/base/cobol_src/BNK1DAC.cbl:1133 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendHbnkL1133() {
        throw new CicsAbendException("HBNK", "BNK1DAC", "src/base/cobol_src/BNK1DAC.cbl:1133");
    }

    /** SEND MAP(BNK1DA) MAPSET(BNK1DAM) FROM(BNK1DAO) at src/base/cobol_src/BNK1DAC.cbl:827, src/base/cobol_src/BNK1DAC.cbl:906, src/base/cobol_src/BNK1DAC.cbl:980 (#3619).
     *  TODO: port the logic that fills BNK1DAO before the SEND.
     *  BMS screen fields field testing: open (3 public / 0 private estates). */
    public Bnk1daScreen renderBnk1da(Bnk1daScreen screen) {
        return screen;
    }

    /** RECEIVE MAP(BNK1DA) MAPSET(BNK1DAM) INTO(BNK1DAI) at src/base/cobol_src/BNK1DAC.cbl:426 (#3619).
     *  `aid` is the key the user pressed (EIBAID): ENTER, PF1-PF24, CLEAR, PA1-PA3.
     *  TODO: port the logic that reads BNK1DAI after the RECEIVE, and return the screen to show next.
     *  BMS screen fields field testing: open (3 public / 0 private estates). */
    public ScreenModel submitBnk1da(Bnk1daScreen input, String aid) {
        return renderBnk1da(input);
    }

}