/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.dto.contract.Bnk1cacSubpgmParms;
import com.gitgalaxy.modernized.dto.contract.Bnk1ccaInqacccuCommarea;
import com.gitgalaxy.modernized.dto.contract.Bnk1dcsInqcustCommarea;
import com.gitgalaxy.modernized.dto.contract.BnkmenuAbndinfoRec;
import com.gitgalaxy.modernized.exception.*;
import com.gitgalaxy.modernized.repository.db2.AccountRepository;
import com.gitgalaxy.modernized.repository.db2.ControlRepository;
import com.gitgalaxy.modernized.repository.db2.ProctranRepository;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

/**
 * Response handling (field testing: field-tested (6 public / 0 private estates)):
 * LINK at line 304 tests NORMAL
 * ENQ at line 390 tests NORMAL
 * DEQ at line 412 tests NORMAL
 * TODO: the RESP of LINK at line 1088 (paragraph CAC010) is never tested
 */
@Service
@Transactional
@RequiredArgsConstructor
public class CreaccService {

    private static final Logger log = LoggerFactory.getLogger(CreaccService.class);

    private final ObjectProvider<InqacccuService> inqacccuService;
    private final ObjectProvider<InqcustService> inqcustService;
    private final ObjectProvider<AbndprocService> abndprocService;
    private final AccountRepository accountRepository;
    private final ControlRepository controlRepository;
    private final ProctranRepository proctranRepository;

    public void executeCreacc(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for CREACC");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public Bnk1cacSubpgmParms handleLink(Bnk1cacSubpgmParms request) {
        log.info("Creacc: handleLink");
        return request;
    }

    /** EXEC CICS LINK PROGRAM(INQACCCU) at src/base/cobol_src/CREACC.cbl:1088.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public Bnk1ccaInqacccuCommarea linkInqacccu(Bnk1ccaInqacccuCommarea request) {
        return inqacccuService.getObject().handleLink(request);
    }

    /** EXEC CICS LINK PROGRAM(INQCUST) at src/base/cobol_src/CREACC.cbl:304.
     *  Call targets field testing: open (6 public / 0 private estates). */
    public Bnk1dcsInqcustCommarea linkInqcust(Bnk1dcsInqcustCommarea request) {
        return inqcustService.getObject().handleLink(request);
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:508: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL508(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:508: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:586: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL586(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:586: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:674: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL674(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:674: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:751: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL751(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:751: no known target " + program);
        }
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:1055: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL1055(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/CREACC.cbl:1055: no known target " + program);
        }
    }

    /**
     * EXEC CICS ABEND ABCODE(HNCS) at src/base/cobol_src/CREACC.cbl:517 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendHncsL517() {
        throw new CicsAbendException("HNCS", "CREACC", "src/base/cobol_src/CREACC.cbl:517");
    }

    /**
     * EXEC CICS ABEND ABCODE(HNCS) at src/base/cobol_src/CREACC.cbl:595 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendHncsL595() {
        throw new CicsAbendException("HNCS", "CREACC", "src/base/cobol_src/CREACC.cbl:595");
    }

    /**
     * EXEC CICS ABEND ABCODE(HNCS) at src/base/cobol_src/CREACC.cbl:683 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendHncsL683() {
        throw new CicsAbendException("HNCS", "CREACC", "src/base/cobol_src/CREACC.cbl:683");
    }

    /**
     * EXEC CICS ABEND ABCODE(HNCS) at src/base/cobol_src/CREACC.cbl:760 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendHncsL760() {
        throw new CicsAbendException("HNCS", "CREACC", "src/base/cobol_src/CREACC.cbl:760");
    }

    /**
     * EXEC CICS ABEND ABCODE(HWPT) at src/base/cobol_src/CREACC.cbl:1059 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendHwptL1059() {
        throw new CicsAbendException("HWPT", "CREACC", "src/base/cobol_src/CREACC.cbl:1059");
    }

}