/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.dto.contract.Bnk1dacParmsSubpgm;
import com.gitgalaxy.modernized.dto.contract.BnkmenuAbndinfoRec;
import com.gitgalaxy.modernized.exception.*;
import com.gitgalaxy.modernized.repository.db2.AccountRepository;
import com.gitgalaxy.modernized.repository.db2.ProctranRepository;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
@RequiredArgsConstructor
public class DelaccService {

    private static final Logger log = LoggerFactory.getLogger(DelaccService.class);

    private final ObjectProvider<AbndprocService> abndprocService;
    private final AccountRepository accountRepository;
    private final ProctranRepository proctranRepository;

    public void executeDelacc(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for DELACC");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public Bnk1dacParmsSubpgm handleLink(Bnk1dacParmsSubpgm request) {
        log.info("Delacc: handleLink");
        return request;
    }

    /** LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/DELACC.cbl:603: the target is data-driven. Candidates: ABNDPROC (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchWsAbendPgmL603(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "ABNDPROC":
                return abndprocService.getObject().handleLink((BnkmenuAbndinfoRec) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(WS-ABEND-PGM) at src/base/cobol_src/DELACC.cbl:603: no known target " + program);
        }
    }

    /**
     * EXEC CICS ABEND ABCODE(HRAC) at src/base/cobol_src/DELACC.cbl:339 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendHracL339() {
        throw new CicsAbendException("HRAC", "DELACC", "src/base/cobol_src/DELACC.cbl:339");
    }

    /**
     * EXEC CICS ABEND ABCODE(HWPT) at src/base/cobol_src/DELACC.cbl:612 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendHwptL612() {
        throw new CicsAbendException("HWPT", "DELACC", "src/base/cobol_src/DELACC.cbl:612");
    }

}