/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.repository.db2;

import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

/**
 * DB2 table ACCOUNT: the embedded SQL of ACCTCTRL, BANKDATA, CREACC, DBCRFUN, DELACC, INQACC, INQACCCU, UPDACC, XFRFUN, one method per statement, as written.
 * Each returns what JDBC returns; mapping onto business types is the service's job.
 * Columns: com.gitgalaxy.modernized.dto.db2.AccountRow.
 * TODO: this SQL is DB2's; the configured database is postgresql -- review each statement.
 */
@Repository
public class AccountRepository {

    private final NamedParameterJdbcTemplate jdbc;

    public AccountRepository(NamedParameterJdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    /** EXEC SQL SELECT at src/base/cobol_src/ACCTCTRL.cbl:165 (ACCTCTRL, read access).
     *  Parameters: hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  The INTO host variables are the columns of the returned row.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public Map<String, Object> selectL165Acctctrl(Map<String, ?> params) {
        return jdbc.queryForMap("""
            SELECT COUNT(*) FROM ACCOUNT WHERE ACCOUNT_SORTCODE = :hvAccountSortcode
            """, params);
    }

    /** EXEC SQL INSERT at src/base/cobol_src/BANKDATA.cbl:808 (BANKDATA, insert access).
     *  Parameters: hvAccountActualBalance = :HV-ACCOUNT-ACTUAL-BALANCE, hvAccountAvailableBalance = :HV-ACCOUNT-AVAILABLE-BALANCE, hvAccountCustNo = :HV-ACCOUNT-CUST-NO, hvAccountEyecatcher = :HV-ACCOUNT-EYECATCHER, hvAccountInterestRate = :HV-ACCOUNT-INTEREST-RATE, hvAccountLastStmtDate = :HV-ACCOUNT-LAST-STMT-DATE, hvAccountNextStmtDate = :HV-ACCOUNT-NEXT-STMT-DATE, hvAccountNumber = :HV-ACCOUNT-NUMBER, hvAccountOpened = :HV-ACCOUNT-OPENED, hvAccountOverdraftLimit = :HV-ACCOUNT-OVERDRAFT-LIMIT, hvAccountSortCode = :HV-ACCOUNT-SORT-CODE, hvAccountType = :HV-ACCOUNT-TYPE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public int insertL808Bankdata(Map<String, ?> params) {
        return jdbc.update("""
            INSERT INTO ACCOUNT (ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE ) VALUES (:hvAccountEyecatcher, :hvAccountCustNo, :hvAccountSortCode, :hvAccountNumber, :hvAccountType, :hvAccountInterestRate, :hvAccountOpened, :hvAccountOverdraftLimit, :hvAccountLastStmtDate, :hvAccountNextStmtDate, :hvAccountAvailableBalance, :hvAccountActualBalance )
            """, params);
    }

    /** EXEC SQL DELETE at src/base/cobol_src/BANKDATA.cbl:1192 (BANKDATA, delete access).
     *  Parameters: hvAccountSortCode = :HV-ACCOUNT-SORT-CODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public int deleteL1192Bankdata(Map<String, ?> params) {
        return jdbc.update("""
            DELETE FROM ACCOUNT WHERE ACCOUNT_SORTCODE = :hvAccountSortCode
            """, params);
    }

    /** EXEC SQL INSERT at src/base/cobol_src/CREACC.cbl:826 (CREACC, insert access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountAccType = :HV-ACCOUNT-ACC-TYPE, hvAccountActualBal = :HV-ACCOUNT-ACTUAL-BAL, hvAccountAvailBal = :HV-ACCOUNT-AVAIL-BAL, hvAccountCustNo = :HV-ACCOUNT-CUST-NO, hvAccountEyecatcher = :HV-ACCOUNT-EYECATCHER, hvAccountIntRate = :HV-ACCOUNT-INT-RATE, hvAccountLastStmt = :HV-ACCOUNT-LAST-STMT, hvAccountNextStmt = :HV-ACCOUNT-NEXT-STMT, hvAccountOpened = :HV-ACCOUNT-OPENED, hvAccountOverdraftLim = :HV-ACCOUNT-OVERDRAFT-LIM, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public int insertL826Creacc(Map<String, ?> params) {
        return jdbc.update("""
            INSERT INTO ACCOUNT (ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE ) VALUES (:hvAccountEyecatcher, :hvAccountCustNo, :hvAccountSortcode, :hvAccountAccNo, :hvAccountAccType, :hvAccountIntRate, :hvAccountOpened, :hvAccountOverdraftLim, :hvAccountLastStmt, :hvAccountNextStmt, :hvAccountAvailBal, :hvAccountActualBal )
            """, params);
    }

    /** EXEC SQL SELECT at src/base/cobol_src/DBCRFUN.cbl:245 (DBCRFUN, read access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  The INTO host variables are the columns of the returned row.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public Map<String, Object> selectL245Dbcrfun(Map<String, ?> params) {
        return jdbc.queryForMap("""
            SELECT ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE FROM ACCOUNT WHERE (ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo)
            """, params);
    }

    /** EXEC SQL UPDATE at src/base/cobol_src/DBCRFUN.cbl:392 (DBCRFUN, update access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountAccType = :HV-ACCOUNT-ACC-TYPE, hvAccountActualBal = :HV-ACCOUNT-ACTUAL-BAL, hvAccountAvailBal = :HV-ACCOUNT-AVAIL-BAL, hvAccountCustNo = :HV-ACCOUNT-CUST-NO, hvAccountEyecatcher = :HV-ACCOUNT-EYECATCHER, hvAccountIntRate = :HV-ACCOUNT-INT-RATE, hvAccountLastStmt = :HV-ACCOUNT-LAST-STMT, hvAccountNextStmt = :HV-ACCOUNT-NEXT-STMT, hvAccountOpened = :HV-ACCOUNT-OPENED, hvAccountOverdraftLim = :HV-ACCOUNT-OVERDRAFT-LIM, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public int updateL392Dbcrfun(Map<String, ?> params) {
        return jdbc.update("""
            UPDATE ACCOUNT SET ACCOUNT_EYECATCHER = :hvAccountEyecatcher, ACCOUNT_CUSTOMER_NUMBER = :hvAccountCustNo, ACCOUNT_SORTCODE = :hvAccountSortcode, ACCOUNT_NUMBER = :hvAccountAccNo, ACCOUNT_TYPE = :hvAccountAccType, ACCOUNT_INTEREST_RATE = :hvAccountIntRate, ACCOUNT_OPENED = :hvAccountOpened, ACCOUNT_OVERDRAFT_LIMIT = :hvAccountOverdraftLim, ACCOUNT_LAST_STATEMENT = :hvAccountLastStmt, ACCOUNT_NEXT_STATEMENT = :hvAccountNextStmt, ACCOUNT_AVAILABLE_BALANCE = :hvAccountAvailBal, ACCOUNT_ACTUAL_BALANCE = :hvAccountActualBal WHERE (ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo)
            """, params);
    }

    /** EXEC SQL SELECT at src/base/cobol_src/DELACC.cbl:248 (DELACC, read access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  The INTO host variables are the columns of the returned row.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public Map<String, Object> selectL248Delacc(Map<String, ?> params) {
        return jdbc.queryForMap("""
            SELECT ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE FROM ACCOUNT WHERE ACCOUNT_NUMBER = :hvAccountAccNo AND ACCOUNT_SORTCODE = :hvAccountSortcode
            """, params);
    }

    /** EXEC SQL DELETE at src/base/cobol_src/DELACC.cbl:438 (DELACC, delete access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public int deleteL438Delacc(Map<String, ?> params) {
        return jdbc.update("""
            DELETE FROM ACCOUNT WHERE ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo
            """, params);
    }

    /** EXEC SQL DECLARE CURSOR at src/base/cobol_src/INQACC.cbl:66 (INQACC, read access).
     *  The cursor's OPEN at line 270, CLOSE at line 350, FETCH at line 431.
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public List<Map<String, Object>> cursorAccCursorL66Inqacc(Map<String, ?> params) {
        return jdbc.queryForList("""
            SELECT ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE FROM ACCOUNT WHERE ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo FOR FETCH ONLY
            """, params);
    }

    /** EXEC SQL SELECT at src/base/cobol_src/INQACC.cbl:843 (INQACC, read access).
     *  Parameters: hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  The INTO host variables are the columns of the returned row.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public Map<String, Object> selectL843Inqacc(Map<String, ?> params) {
        return jdbc.queryForMap("""
            SELECT ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE FROM ACCOUNT WHERE ACCOUNT_SORTCODE = :hvAccountSortcode ORDER BY ACCOUNT_NUMBER DESC FETCH FIRST 1 ROWS ONLY
            """, params);
    }

    /** EXEC SQL DECLARE CURSOR at src/base/cobol_src/INQACCCU.cbl:74 (INQACCCU, read access).
     *  The cursor's OPEN at line 246, CLOSE at line 348, FETCH at line 466.
     *  Parameters: hvAccountCustNo = :HV-ACCOUNT-CUST-NO, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public List<Map<String, Object>> cursorAccCursorL74Inqacccu(Map<String, ?> params) {
        return jdbc.queryForList("""
            SELECT ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE FROM ACCOUNT WHERE ACCOUNT_CUSTOMER_NUMBER = :hvAccountCustNo AND ACCOUNT_SORTCODE = :hvAccountSortcode FOR FETCH ONLY
            """, params);
    }

    /** EXEC SQL SELECT at src/base/cobol_src/UPDACC.cbl:191 (UPDACC, read access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  The INTO host variables are the columns of the returned row.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public Map<String, Object> selectL191Updacc(Map<String, ?> params) {
        return jdbc.queryForMap("""
            SELECT ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE FROM ACCOUNT WHERE (ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo)
            """, params);
    }

    /** EXEC SQL UPDATE at src/base/cobol_src/UPDACC.cbl:278 (UPDACC, update access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountAccType = :HV-ACCOUNT-ACC-TYPE, hvAccountIntRate = :HV-ACCOUNT-INT-RATE, hvAccountOverdraftLim = :HV-ACCOUNT-OVERDRAFT-LIM, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public int updateL278Updacc(Map<String, ?> params) {
        return jdbc.update("""
            UPDATE ACCOUNT SET ACCOUNT_TYPE = :hvAccountAccType, ACCOUNT_INTEREST_RATE = :hvAccountIntRate, ACCOUNT_OVERDRAFT_LIMIT = :hvAccountOverdraftLim WHERE (ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo)
            """, params);
    }

    /** EXEC SQL SELECT at src/base/cobol_src/XFRFUN.cbl:930 (XFRFUN, read access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  The INTO host variables are the columns of the returned row.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public Map<String, Object> selectL930Xfrfun(Map<String, ?> params) {
        return jdbc.queryForMap("""
            SELECT ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE FROM ACCOUNT WHERE (ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo)
            """, params);
    }

    /** EXEC SQL UPDATE at src/base/cobol_src/XFRFUN.cbl:992 (XFRFUN, update access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountAccType = :HV-ACCOUNT-ACC-TYPE, hvAccountActualBal = :HV-ACCOUNT-ACTUAL-BAL, hvAccountAvailBal = :HV-ACCOUNT-AVAIL-BAL, hvAccountCustNo = :HV-ACCOUNT-CUST-NO, hvAccountEyecatcher = :HV-ACCOUNT-EYECATCHER, hvAccountIntRate = :HV-ACCOUNT-INT-RATE, hvAccountLastStmt = :HV-ACCOUNT-LAST-STMT, hvAccountNextStmt = :HV-ACCOUNT-NEXT-STMT, hvAccountOpened = :HV-ACCOUNT-OPENED, hvAccountOverdraftLim = :HV-ACCOUNT-OVERDRAFT-LIM, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public int updateL992Xfrfun(Map<String, ?> params) {
        return jdbc.update("""
            UPDATE ACCOUNT SET ACCOUNT_EYECATCHER = :hvAccountEyecatcher, ACCOUNT_CUSTOMER_NUMBER = :hvAccountCustNo, ACCOUNT_SORTCODE = :hvAccountSortcode, ACCOUNT_NUMBER = :hvAccountAccNo, ACCOUNT_TYPE = :hvAccountAccType, ACCOUNT_INTEREST_RATE = :hvAccountIntRate, ACCOUNT_OPENED = :hvAccountOpened, ACCOUNT_OVERDRAFT_LIMIT = :hvAccountOverdraftLim, ACCOUNT_LAST_STATEMENT = :hvAccountLastStmt, ACCOUNT_NEXT_STATEMENT = :hvAccountNextStmt, ACCOUNT_AVAILABLE_BALANCE = :hvAccountAvailBal, ACCOUNT_ACTUAL_BALANCE = :hvAccountActualBal WHERE (ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo)
            """, params);
    }

    /** EXEC SQL SELECT at src/base/cobol_src/XFRFUN.cbl:1057 (XFRFUN, read access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  The INTO host variables are the columns of the returned row.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public Map<String, Object> selectL1057Xfrfun(Map<String, ?> params) {
        return jdbc.queryForMap("""
            SELECT ACCOUNT_EYECATCHER, ACCOUNT_CUSTOMER_NUMBER, ACCOUNT_SORTCODE, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_INTEREST_RATE, ACCOUNT_OPENED, ACCOUNT_OVERDRAFT_LIMIT, ACCOUNT_LAST_STATEMENT, ACCOUNT_NEXT_STATEMENT, ACCOUNT_AVAILABLE_BALANCE, ACCOUNT_ACTUAL_BALANCE FROM ACCOUNT WHERE (ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo)
            """, params);
    }

    /** EXEC SQL UPDATE at src/base/cobol_src/XFRFUN.cbl:1362 (XFRFUN, update access).
     *  Parameters: hvAccountAccNo = :HV-ACCOUNT-ACC-NO, hvAccountAccType = :HV-ACCOUNT-ACC-TYPE, hvAccountActualBal = :HV-ACCOUNT-ACTUAL-BAL, hvAccountAvailBal = :HV-ACCOUNT-AVAIL-BAL, hvAccountCustNo = :HV-ACCOUNT-CUST-NO, hvAccountEyecatcher = :HV-ACCOUNT-EYECATCHER, hvAccountIntRate = :HV-ACCOUNT-INT-RATE, hvAccountLastStmt = :HV-ACCOUNT-LAST-STMT, hvAccountNextStmt = :HV-ACCOUNT-NEXT-STMT, hvAccountOpened = :HV-ACCOUNT-OPENED, hvAccountOverdraftLim = :HV-ACCOUNT-OVERDRAFT-LIM, hvAccountSortcode = :HV-ACCOUNT-SORTCODE.
     *  DB2 table access field testing: open (3 public / 0 private estates). */
    public int updateL1362Xfrfun(Map<String, ?> params) {
        return jdbc.update("""
            UPDATE ACCOUNT SET ACCOUNT_EYECATCHER = :hvAccountEyecatcher, ACCOUNT_CUSTOMER_NUMBER = :hvAccountCustNo, ACCOUNT_SORTCODE = :hvAccountSortcode, ACCOUNT_NUMBER = :hvAccountAccNo, ACCOUNT_TYPE = :hvAccountAccType, ACCOUNT_INTEREST_RATE = :hvAccountIntRate, ACCOUNT_OPENED = :hvAccountOpened, ACCOUNT_OVERDRAFT_LIMIT = :hvAccountOverdraftLim, ACCOUNT_LAST_STATEMENT = :hvAccountLastStmt, ACCOUNT_NEXT_STATEMENT = :hvAccountNextStmt, ACCOUNT_AVAILABLE_BALANCE = :hvAccountAvailBal, ACCOUNT_ACTUAL_BALANCE = :hvAccountActualBal WHERE (ACCOUNT_SORTCODE = :hvAccountSortcode AND ACCOUNT_NUMBER = :hvAccountAccNo)
            """, params);
    }

}