/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.entity.vsam;

import jakarta.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The key of OutputData: CUSTOMER-SORTCODE, CUSTOMER-NUMBER together (offset 4, 16 bytes, from IDCAMS KEYS): the @EmbeddedId OutputDataKey.
 */
@Embeddable
@Data
@NoArgsConstructor
public class OutputDataKey implements Serializable {

    // CUSTOMER-SORTCODE: PIC 9(6), offset 4, 6 bytes
    @Column(name = "CUSTOMER_SORTCODE")
    private Integer customerSortcode;

    // CUSTOMER-NUMBER: PIC 9(10), offset 10, 10 bytes
    @Column(name = "CUSTOMER_NUMBER")
    private Long customerNumber;

}