/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-banking-sample-application-cbsa at commit 417334533178ab6e753cc64b0e0e5cf0b4952704,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.dto.screen;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BMS map BNK1CC of mapset BNK1CCM (src/base/bms_src/BNK1CCM.bms): the screen as a view model (#3619).
 * SEND at src/base/cobol_src/BNK1CCS.cbl:1286, src/base/cobol_src/BNK1CCS.cbl:1364, src/base/cobol_src/BNK1CCS.cbl:1441; RECEIVE at src/base/cobol_src/BNK1CCS.cbl:500.
 * One property per named field (symbolic map BNK1CCI / BNK1CCO); LAYOUT is every field in
 * screen order, labels included. BMS screen fields field testing: open (3 public / 0 private estates).
 */
@Data
@NoArgsConstructor
public class Bnk1ccScreen implements ScreenModel {

    public static final String MAPSET = "BNK1CCM";
    public static final String MAP = "BNK1CC";
    public static final List<ScreenField> LAYOUT = List.of(
            new ScreenField(null, 1, 1, 7, false, false, false, false, false, "BNK1CC ", "BLUE", 1),
            new ScreenField("COMPANY", 1, 16, 52, false, false, false, false, false, "CICS Bank Sample Application - Create Customer.", "RED", 1),
            new ScreenField(null, 3, 1, 46, false, false, false, false, false, "Provide a Name, Address and D.O.B. then Enter ", "TURQUOISE", 1),
            new ScreenField(null, 7, 1, 16, false, false, false, false, false, " Customer Title", "NEUTRAL", 1),
            new ScreenField("CUSTTIT", 7, 18, 10, true, false, false, false, true, null, "GREEN", 1),
            new ScreenField(null, 7, 29, 0, false, false, false, false, false, null, "NEUTRAL", 1),
            new ScreenField(null, 7, 31, 14, false, false, false, false, false, "First Name", "NEUTRAL", 1),
            new ScreenField("CHRISTN", 7, 46, 20, true, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 7, 67, 0, false, false, false, false, false, null, "NEUTRAL", 1),
            new ScreenField(null, 8, 1, 16, false, false, false, false, false, " Middle Initials", "NEUTRAL", 1),
            new ScreenField("CUSTINS", 8, 18, 2, true, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 8, 21, 0, false, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 8, 22, 12, false, false, false, false, false, "Family name ", "NEUTRAL", 1),
            new ScreenField("CUSTSN", 8, 35, 20, true, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 8, 56, 1, false, false, false, false, false, null, null, 1),
            new ScreenField(null, 10, 1, 16, false, false, false, false, false, " Customer Addr1 ", "NEUTRAL", 1),
            new ScreenField("CUSTAD1", 10, 18, 60, true, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 10, 79, 0, false, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 11, 1, 16, false, false, false, false, false, " Customer Addr2 ", "NEUTRAL", 1),
            new ScreenField("CUSTAD2", 11, 18, 60, true, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 11, 79, 0, false, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 12, 1, 16, false, false, false, false, false, " Customer Addr3 ", "NEUTRAL", 1),
            new ScreenField("CUSTAD3", 12, 18, 40, true, false, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 12, 59, 1, false, false, false, false, false, null, null, 1),
            new ScreenField(null, 13, 1, 16, false, false, false, false, false, " Customer D.O.B.", "NEUTRAL", 1),
            new ScreenField("DOBDD", 13, 18, 2, true, true, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 13, 21, 1, false, false, false, false, false, "/", "NEUTRAL", 1),
            new ScreenField("DOBMM", 13, 23, 2, true, true, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 13, 26, 1, false, false, false, false, false, "/", "NEUTRAL", 1),
            new ScreenField("DOBYY", 13, 28, 4, true, true, false, false, false, null, "GREEN", 1),
            new ScreenField(null, 13, 33, 1, false, false, false, false, false, null, null, 1),
            new ScreenField(null, 15, 1, 16, false, false, false, false, false, " Sort Code     ", "NEUTRAL", 1),
            new ScreenField("SORTC", 15, 18, 6, false, true, false, false, false, null, "NEUTRAL", 1),
            new ScreenField(null, 16, 1, 16, false, false, false, false, false, " Customer Number", "NEUTRAL", 1),
            new ScreenField("CUSTNO2", 16, 18, 10, false, true, false, false, false, null, "NEUTRAL", 1),
            new ScreenField(null, 17, 1, 16, false, false, false, false, false, " Credit Score   ", "NEUTRAL", 1),
            new ScreenField("CREDSC", 17, 18, 3, false, true, false, false, false, null, "NEUTRAL", 1),
            new ScreenField(null, 18, 1, 16, false, false, false, false, false, " CS Review Date ", "NEUTRAL", 1),
            new ScreenField("SCRDTDD", 18, 18, 2, false, true, false, false, false, null, "NEUTRAL", 1),
            new ScreenField(null, 18, 21, 1, false, false, false, false, false, "/", "NEUTRAL", 1),
            new ScreenField("SCRDTMM", 18, 23, 2, false, true, false, false, false, null, "NEUTRAL", 1),
            new ScreenField(null, 18, 26, 1, false, false, false, false, false, "/", "NEUTRAL", 1),
            new ScreenField("SCRDTYY", 18, 28, 4, false, true, false, false, false, null, "NEUTRAL", 1),
            new ScreenField("MESSAGE", 23, 1, 79, false, false, true, false, false, null, "YELLOW", 1),
            new ScreenField(null, 24, 1, 20, false, false, false, false, false, "F3=Exit   F12=Cancel", "BLUE", 1),
            new ScreenField("DUMMY", 24, 79, 1, false, false, false, true, false, " ", null, 1));

    /** COMPANY: (1,16), 52 bytes, ATTRB=NORM,PROT -- src/base/bms_src/BNK1CCM.bms:30. Symbolic map COMPANYI, COMPANYO. */
    private String company;

    /** CUSTTIT: (7,18), 10 bytes, ATTRB=FSET,IC,NORM,UNPROT -- src/base/bms_src/BNK1CCM.bms:38. Symbolic map CUSTTITI, CUSTTITO. */
    private String custtit;

    /** CHRISTN: (7,46), 20 bytes, ATTRB=FSET,NORM,UNPROT -- src/base/bms_src/BNK1CCM.bms:45. Symbolic map CHRISTNI, CHRISTNO. */
    private String christn;

    /** CUSTINS: (8,18), 2 bytes, ATTRB=FSET,NORM,UNPROT -- src/base/bms_src/BNK1CCM.bms:52. Symbolic map CUSTINSI, CUSTINSO. */
    private String custins;

    /** CUSTSN: (8,35), 20 bytes, ATTRB=FSET,NORM,UNPROT -- src/base/bms_src/BNK1CCM.bms:59. Symbolic map CUSTSNI, CUSTSNO. */
    private String custsn;

    /** CUSTAD1: (10,18), 60 bytes, ATTRB=FSET,NORM,UNPROT -- src/base/bms_src/BNK1CCM.bms:65. Symbolic map CUSTAD1I, CUSTAD1O. */
    private String custad1;

    /** CUSTAD2: (11,18), 60 bytes, ATTRB=FSET,NORM,UNPROT -- src/base/bms_src/BNK1CCM.bms:72. Symbolic map CUSTAD2I, CUSTAD2O. */
    private String custad2;

    /** CUSTAD3: (12,18), 40 bytes, ATTRB=FSET,NORM,UNPROT -- src/base/bms_src/BNK1CCM.bms:79. Symbolic map CUSTAD3I, CUSTAD3O. */
    private String custad3;

    /** DOBDD: (13,18), 2 bytes, ATTRB=FSET,NORM,NUM,UNPROT -- src/base/bms_src/BNK1CCM.bms:85. Symbolic map DOBDDI, DOBDDO. */
    private String dobdd;

    /** DOBMM: (13,23), 2 bytes, ATTRB=FSET,NORM,NUM,UNPROT -- src/base/bms_src/BNK1CCM.bms:89. Symbolic map DOBMMI, DOBMMO. */
    private String dobmm;

    /** DOBYY: (13,28), 4 bytes, ATTRB=FSET,NORM,NUM,UNPROT -- src/base/bms_src/BNK1CCM.bms:93. Symbolic map DOBYYI, DOBYYO. */
    private String dobyy;

    /** SORTC: (15,18), 6 bytes, ATTRB=FSET,NORM,NUM,PROT -- src/base/bms_src/BNK1CCM.bms:98. Symbolic map SORTCI, SORTCO. */
    private String sortc;

    /** CUSTNO2: (16,18), 10 bytes, ATTRB=FSET,NORM,NUM,PROT -- src/base/bms_src/BNK1CCM.bms:102. Symbolic map CUSTNO2I, CUSTNO2O. */
    private String custno2;

    /** CREDSC: (17,18), 3 bytes, ATTRB=FSET,NORM,NUM,PROT -- src/base/bms_src/BNK1CCM.bms:106. Symbolic map CREDSCI, CREDSCO. */
    private String credsc;

    /** SCRDTDD: (18,18), 2 bytes, ATTRB=FSET,NORM,NUM,PROT -- src/base/bms_src/BNK1CCM.bms:110. Symbolic map SCRDTDDI, SCRDTDDO. */
    private String scrdtdd;

    /** SCRDTMM: (18,23), 2 bytes, ATTRB=FSET,NORM,NUM,PROT -- src/base/bms_src/BNK1CCM.bms:114. Symbolic map SCRDTMMI, SCRDTMMO. */
    private String scrdtmm;

    /** SCRDTYY: (18,28), 4 bytes, ATTRB=FSET,NORM,NUM,PROT -- src/base/bms_src/BNK1CCM.bms:118. Symbolic map SCRDTYYI, SCRDTYYO. */
    private String scrdtyy;

    /** MESSAGE: (23,1), 79 bytes, ATTRB=BRT,PROT -- src/base/bms_src/BNK1CCM.bms:121. Symbolic map MESSAGEI, MESSAGEO. */
    private String message;

    /** DUMMY: (24,79), 1 bytes, ATTRB=DRK,FSET,PROT -- src/base/bms_src/BNK1CCM.bms:124. Symbolic map DUMMYI, DUMMYO. */
    private String dummy;

    @Override
    public String mapsetName() {
        return MAPSET;
    }

    @Override
    public String mapName() {
        return MAP;
    }

    @Override
    public List<ScreenField> screenLayout() {
        return LAYOUT;
    }

    @Override
    public Map<String, String> screenValues() {
        Map<String, String> values = new LinkedHashMap<>();
        values.put("COMPANY", company);
        values.put("CUSTTIT", custtit);
        values.put("CHRISTN", christn);
        values.put("CUSTINS", custins);
        values.put("CUSTSN", custsn);
        values.put("CUSTAD1", custad1);
        values.put("CUSTAD2", custad2);
        values.put("CUSTAD3", custad3);
        values.put("DOBDD", dobdd);
        values.put("DOBMM", dobmm);
        values.put("DOBYY", dobyy);
        values.put("SORTC", sortc);
        values.put("CUSTNO2", custno2);
        values.put("CREDSC", credsc);
        values.put("SCRDTDD", scrdtdd);
        values.put("SCRDTMM", scrdtmm);
        values.put("SCRDTYY", scrdtyy);
        values.put("MESSAGE", message);
        values.put("DUMMY", dummy);
        return values;
    }

    /** A view model from posted form values (keys as `screenValues` writes them). */
    public static Bnk1ccScreen fromValues(Map<String, String> values) {
        Bnk1ccScreen screen = new Bnk1ccScreen();
        screen.setCompany(values.get("COMPANY"));
        screen.setCusttit(values.get("CUSTTIT"));
        screen.setChristn(values.get("CHRISTN"));
        screen.setCustins(values.get("CUSTINS"));
        screen.setCustsn(values.get("CUSTSN"));
        screen.setCustad1(values.get("CUSTAD1"));
        screen.setCustad2(values.get("CUSTAD2"));
        screen.setCustad3(values.get("CUSTAD3"));
        screen.setDobdd(values.get("DOBDD"));
        screen.setDobmm(values.get("DOBMM"));
        screen.setDobyy(values.get("DOBYY"));
        screen.setSortc(values.get("SORTC"));
        screen.setCustno2(values.get("CUSTNO2"));
        screen.setCredsc(values.get("CREDSC"));
        screen.setScrdtdd(values.get("SCRDTDD"));
        screen.setScrdtmm(values.get("SCRDTMM"));
        screen.setScrdtyy(values.get("SCRDTYY"));
        screen.setMessage(values.get("MESSAGE"));
        screen.setDummy(values.get("DUMMY"));
        return screen;
    }
}
