/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-genapp at commit f6f3f4b2580d31b7d8dcc31ce3e3676f4cceaaaa,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.service;

import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.gitgalaxy.modernized.client.Dor1RemoteClient;
import com.gitgalaxy.modernized.dto.contract.Lgacdb01CaErrorMsg;
import com.gitgalaxy.modernized.dto.contract.Lgtestp1CommArea;
import com.gitgalaxy.modernized.dto.contract.Lgupol01Dfhcommarea;
import com.gitgalaxy.modernized.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
@RequiredArgsConstructor
public class Lgupol01Service {

    private static final Logger log = LoggerFactory.getLogger(Lgupol01Service.class);

    private final Dor1RemoteClient dor1RemoteClient;
    private final ObjectProvider<LgstsqService> lgstsqService;
    private final ObjectProvider<Lgupdb01Service> lgupdb01Service;

    public void executeLgupol01(/* Parameters mapped from Controller */) {
        log.info("Executing modernized business logic for lgupol01");
        // TODO: [AI AGENT] Implement extracted business rules here.
    }

    /** Another program LINKed / XCTLed to this one. TODO: [AI AGENT] implement from the program's business rules. */
    public Lgtestp1CommArea handleLink(Lgtestp1CommArea request) {
        log.info("Lgupol01: handleLink");
        return request;
    }

    /** EXEC CICS LINK PROGRAM(LGUPDB01) at 157: the CSD routes it to region DOR1 (distributed program link).
     *  Remote calls field testing: open (5 public / 0 private estates). */
    public Lgupol01Dfhcommarea remoteLgupdb01L157(Lgupol01Dfhcommarea request) {
        return dor1RemoteClient.linkLgupdb01(request);
    }

    /** EXEC CICS LINK PROGRAM(LGSTSQ) at base/src/lgupol01.cbl:181, base/src/lgupol01.cbl:189, base/src/lgupol01.cbl:195.
     *  Call targets field testing: open (6 public / 0 private estates). */
    // TODO: this site passes ERROR-MSG; LGSTSQ receives CA-ERROR-MSG (base/src/lgacdb01.cbl) -- map one layout onto the other
    public Lgacdb01CaErrorMsg linkLgstsq(Lgacdb01CaErrorMsg request) {
        return lgstsqService.getObject().handleLink(request);
    }

    /** LINK PROGRAM(LGUPDB01) at base/src/lgupol01.cbl:157: the target is data-driven. Candidates: LGUPDB01 (value).
     *  Dynamic call targets field testing: open (5 public / 0 private estates). */
    public Object dispatchLgupdb01L157(String program, Object request) {
        switch (program.trim().toUpperCase()) {
            case "LGUPDB01":
                return lgupdb01Service.getObject().handleLink((Lgupol01Dfhcommarea) request);
            default:
                throw new IllegalArgumentException("LINK PROGRAM(LGUPDB01) at base/src/lgupol01.cbl:157: no known target " + program);
        }
    }

    /**
     * EXEC CICS ABEND ABCODE(LGCA) at base/src/lgupol01.cbl:102 (paragraph paragraph).
     * Units of work and handlers field testing: field-tested (6 public / 0 private estates).
     * Note: resolved at run time if an identifier.
     */
    public void abendLgcaL102() {
        throw new CicsAbendException("LGCA", "LGUPOL01", "base/src/lgupol01.cbl:102");
    }

}