/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/cicsdev/cics-genapp at commit f6f3f4b2580d31b7d8dcc31ce3e3676f4cceaaaa,
 * which is licensed EPL-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.entity;

import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
@Entity
@Table(name = "COMM_AREA")
public class Lgtestc1CommArea {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sys_id")
    private Long sysId;

    @Column(name = "WS_RESP")
    private Integer wsResp;

    @Column(name = "WS_ITEM_COUNT")
    private Integer wsItemCount;

    @Column(name = "WS_FLAG_TSQH")
    private String wsFlagTsqh = "N/A";

    @Column(name = "READ_MSG_MSG")
    private String readMsgMsg;

    @Column(name = "WRITE_MSG_E")
    private String writeMsgE;

    @Column(name = "WRITE_MSG_L")
    private String writeMsgL;

    @Column(name = "WRITE_MSG_LOW")
    private Integer writeMsgLow;

    @Column(name = "WRITE_MSG_H")
    private String writeMsgH;

    @Column(name = "WRITE_MSG_HIGH")
    private Integer writeMsgHigh;

    @Column(name = "STSQ_NAME")
    private String stsqName;

    @Column(name = "F24")
    private Integer f24;

    @Column(name = "MSGEND")
    private String msgend;

}