/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.exception;

public class CicsConditionException extends RuntimeException {
    private final String condition;
    private final String program;
    private final String site;

    public CicsConditionException(String condition, String program, String site) {
        super("CICS Condition " + condition + " at " + site);
        this.condition = condition;
        this.program = program;
        this.site = site;
    }

    public String getCondition() { return condition; }
    public String getProgram() { return program; }
    public String getSite() { return site; }
}
