/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.entity.vsam;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.List;

/**
 * VSAM INDEXED AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS (app/jcl/ACCTFILE.jcl:36),
 * record ACCOUNT-RECORD (app/cpy/CVACT01Y.cpy, 300 bytes, RECORDSIZE 300).
 * Key: ACCT-ID (offset 0, 11 bytes, from IDCAMS KEYS).
 * CICS files: ACCTDAT.
 * Generated from GitGalaxy's verified skeleton; VSAM defines field testing: open (3 public / 0 private estates).
 */
@Entity(name = "VsamAccountRecord")
@Table(name = "vsam_acctdata")
@Data
@NoArgsConstructor
public class AccountRecord {

    // ACCT-ID: PIC 9(11), offset 0, 11 bytes
    @Id
    @Column(name = "ACCT_ID")
    private Long acctId;

    // ACCT-ACTIVE-STATUS: PIC X(01), offset 11, 1 bytes
    @Column(name = "ACCT_ACTIVE_STATUS", length = 1)
    private String acctActiveStatus;

    // ACCT-CURR-BAL: PIC S9(10)V99, offset 12, 12 bytes
    @Column(name = "ACCT_CURR_BAL")
    private BigDecimal acctCurrBal;

    // ACCT-CREDIT-LIMIT: PIC S9(10)V99, offset 24, 12 bytes
    @Column(name = "ACCT_CREDIT_LIMIT")
    private BigDecimal acctCreditLimit;

    // ACCT-CASH-CREDIT-LIMIT: PIC S9(10)V99, offset 36, 12 bytes
    @Column(name = "ACCT_CASH_CREDIT_LIMIT")
    private BigDecimal acctCashCreditLimit;

    // ACCT-OPEN-DATE: PIC X(10), offset 48, 10 bytes
    @Column(name = "ACCT_OPEN_DATE", length = 10)
    private String acctOpenDate;

    // ACCT-EXPIRAION-DATE: PIC X(10), offset 58, 10 bytes
    @Column(name = "ACCT_EXPIRAION_DATE", length = 10)
    private String acctExpiraionDate;

    // ACCT-REISSUE-DATE: PIC X(10), offset 68, 10 bytes
    @Column(name = "ACCT_REISSUE_DATE", length = 10)
    private String acctReissueDate;

    // ACCT-CURR-CYC-CREDIT: PIC S9(10)V99, offset 78, 12 bytes
    @Column(name = "ACCT_CURR_CYC_CREDIT")
    private BigDecimal acctCurrCycCredit;

    // ACCT-CURR-CYC-DEBIT: PIC S9(10)V99, offset 90, 12 bytes
    @Column(name = "ACCT_CURR_CYC_DEBIT")
    private BigDecimal acctCurrCycDebit;

    // ACCT-ADDR-ZIP: PIC X(10), offset 102, 10 bytes
    @Column(name = "ACCT_ADDR_ZIP", length = 10)
    private String acctAddrZip;

    // ACCT-GROUP-ID: PIC X(10), offset 112, 10 bytes
    @Column(name = "ACCT_GROUP_ID", length = 10)
    private String acctGroupId;


    /** #3624: this record from its fixed-width VSAM form (300 bytes, as REPRO unloads it), each
     *  field at its COBOL offset; `text` is the record's character set (ISO-8859-1 for an ASCII
     *  transfer, IBM037 on z/OS). FILLER bytes are not kept. */
    public static AccountRecord fromRecord(byte[] rec, java.nio.charset.Charset text) {
        AccountRecord r = new AccountRecord();
        r.acctId = CobolRecords.toLong(CobolRecords.zoned(rec, 0, 11, 0, text));
        r.acctActiveStatus = CobolRecords.text(rec, 11, 1, text);
        r.acctCurrBal = CobolRecords.zoned(rec, 12, 12, 2, text);
        r.acctCreditLimit = CobolRecords.zoned(rec, 24, 12, 2, text);
        r.acctCashCreditLimit = CobolRecords.zoned(rec, 36, 12, 2, text);
        r.acctOpenDate = CobolRecords.text(rec, 48, 10, text);
        r.acctExpiraionDate = CobolRecords.text(rec, 58, 10, text);
        r.acctReissueDate = CobolRecords.text(rec, 68, 10, text);
        r.acctCurrCycCredit = CobolRecords.zoned(rec, 78, 12, 2, text);
        r.acctCurrCycDebit = CobolRecords.zoned(rec, 90, 12, 2, text);
        r.acctAddrZip = CobolRecords.text(rec, 102, 10, text);
        r.acctGroupId = CobolRecords.text(rec, 112, 10, text);
        return r;
    }

    /** #3624: the fixed-width VSAM record of this entity (FILLER as spaces). */
    public byte[] toRecord(java.nio.charset.Charset text) {
        byte[] rec = CobolRecords.blank(300, text);
        CobolRecords.putZoned(rec, 0, 11, 0, false, CobolRecords.decimal(acctId), text);
        CobolRecords.putText(rec, 11, 1, acctActiveStatus, text);
        CobolRecords.putZoned(rec, 12, 12, 2, true, CobolRecords.decimal(acctCurrBal), text);
        CobolRecords.putZoned(rec, 24, 12, 2, true, CobolRecords.decimal(acctCreditLimit), text);
        CobolRecords.putZoned(rec, 36, 12, 2, true, CobolRecords.decimal(acctCashCreditLimit), text);
        CobolRecords.putText(rec, 48, 10, acctOpenDate, text);
        CobolRecords.putText(rec, 58, 10, acctExpiraionDate, text);
        CobolRecords.putText(rec, 68, 10, acctReissueDate, text);
        CobolRecords.putZoned(rec, 78, 12, 2, true, CobolRecords.decimal(acctCurrCycCredit), text);
        CobolRecords.putZoned(rec, 90, 12, 2, true, CobolRecords.decimal(acctCurrCycDebit), text);
        CobolRecords.putText(rec, 102, 10, acctAddrZip, text);
        CobolRecords.putText(rec, 112, 10, acctGroupId, text);
        return rec;
    }
}