/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.entity.vsam;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.util.List;

/**
 * VSAM INDEXED AWS.M2.CARDDEMO.CARDXREF.VSAM.KSDS (app/jcl/XREFFILE.jcl:39),
 * record CARD-XREF-RECORD (app/cpy/CVACT03Y.cpy, 50 bytes, RECORDSIZE 50).
 * Key: XREF-CARD-NUM (offset 0, 16 bytes, from IDCAMS KEYS).
 * CICS files: CCXREF, CXACAIX (path AWS.M2.CARDDEMO.CARDXREF.VSAM.AIX.PATH).
 * Generated from GitGalaxy's verified skeleton; VSAM defines field testing: open (3 public / 0 private estates).
 */
@Entity(name = "VsamCardXrefRecord")
@Table(name = "vsam_cardxref")
@Data
@NoArgsConstructor
public class CardXrefRecord {

    // XREF-CARD-NUM: PIC X(16), offset 0, 16 bytes
    @Id
    @Column(name = "XREF_CARD_NUM", length = 16)
    private String xrefCardNum;

    // XREF-CUST-ID: PIC 9(09), offset 16, 9 bytes
    @Column(name = "XREF_CUST_ID")
    private Integer xrefCustId;

    // XREF-ACCT-ID: PIC 9(11), offset 25, 11 bytes
    @Column(name = "XREF_ACCT_ID")
    private Long xrefAcctId;


    /** #3624: this record from its fixed-width VSAM form (50 bytes, as REPRO unloads it), each
     *  field at its COBOL offset; `text` is the record's character set (ISO-8859-1 for an ASCII
     *  transfer, IBM037 on z/OS). FILLER bytes are not kept. */
    public static CardXrefRecord fromRecord(byte[] rec, java.nio.charset.Charset text) {
        CardXrefRecord r = new CardXrefRecord();
        r.xrefCardNum = CobolRecords.text(rec, 0, 16, text);
        r.xrefCustId = CobolRecords.toInteger(CobolRecords.zoned(rec, 16, 9, 0, text));
        r.xrefAcctId = CobolRecords.toLong(CobolRecords.zoned(rec, 25, 11, 0, text));
        return r;
    }

    /** #3624: the fixed-width VSAM record of this entity (FILLER as spaces). */
    public byte[] toRecord(java.nio.charset.Charset text) {
        byte[] rec = CobolRecords.blank(50, text);
        CobolRecords.putText(rec, 0, 16, xrefCardNum, text);
        CobolRecords.putZoned(rec, 16, 9, 0, false, CobolRecords.decimal(xrefCustId), text);
        CobolRecords.putZoned(rec, 25, 11, 0, false, CobolRecords.decimal(xrefAcctId), text);
        return rec;
    }
}