/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.batch;

import com.gitgalaxy.modernized.service.PaudbunlService;
import java.util.List;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.transaction.PlatformTransactionManager;

/** JCL job UNLDPADB (app/app-authorization-ims-db2-mq/jcl/UNLDPADB.JCL) as a Spring Batch job (#3622): its steps in JCL order,
 *  each bypassed when its COND= (or the job's) is satisfied, as JCL does.
 *  Dataset flow: produces AWS.M2.CARDDEMO.PAUTDB.CHILD.FILEO (step STEP01), read by app/app-authorization-ims-db2-mq/jcl/LOADPADB.JCL step STEP01.
 *  Dataset flow: produces AWS.M2.CARDDEMO.PAUTDB.ROOT.FILEO (step STEP01), read by app/app-authorization-ims-db2-mq/jcl/LOADPADB.JCL step STEP01.
 *  JCL job flow field testing: open (5 public / 0 private estates). */
@Configuration
public class UnldpadbJobConfig {

    static final List<Dd> DDS_STEP0 = List.of(new Dd("DD1", "AWS.M2.CARDDEMO.PAUTDB.ROOT.FILEO", "OLD", "DELETE", null), new Dd("DD2", "AWS.M2.CARDDEMO.PAUTDB.CHILD.FILEO", "OLD", "DELETE", null));
    static final List<Dd> DDS_STEP01 = List.of(new Dd("STEPLIB", "OEMA.IMS.IMSP.SDFSRESL", "SHR", null, null), new Dd("STEPLIB", "OEMA.IMS.IMSP.SDFSRESL.V151", "SHR", null, null), new Dd("STEPLIB", "AWS.M2.CARDDEMO.LOADLIB", "SHR", null, null), new Dd("DFSRESLB", "OEMA.IMS.IMSP.SDFSRESL", "SHR", null, null), new Dd("IMS", "OEM.IMS.IMSP.PSBLIB", "SHR", null, null), new Dd("IMS", "OEM.IMS.IMSP.DBDLIB", "SHR", null, null), new Dd("OUTFIL1", "AWS.M2.CARDDEMO.PAUTDB.ROOT.FILEO", "NEW", "CATLG", null), new Dd("OUTFIL2", "AWS.M2.CARDDEMO.PAUTDB.CHILD.FILEO", "NEW", "CATLG", null), new Dd("DDPAUTP0", "OEM.IMS.IMSP.PAUTHDB", "SHR", null, null), new Dd("DDPAUTX0", "OEM.IMS.IMSP.PAUTHDBX", "SHR", null, null), new Dd("DFSVSAMP", "OEMPP.IMS.V15R01MB.PROCLIB(DFSVSMDB)", "SHR", null, null));

    @Bean
    public Job unldpadbJob(JobRepository jobRepository, PlatformTransactionManager tx, JclSteps steps, PaudbunlService paudbunlService) {
        return new JobBuilder("UNLDPADB", jobRepository)
                .start(new StepBuilder("STEP0", jobRepository)
                        .tasklet(steps.iefbr14("STEP0", "STEP0", null, null, null, DDS_STEP0), tx).build())
                .next(new StepBuilder("STEP01", jobRepository)
                        .tasklet(steps.program("STEP01", "STEP01", null, null, null, () -> paudbunlService.runBatch(DDS_STEP01, "DLI,PAUDBUNL,PAUTBUNL,,,,,,,,,,,N")), tx).build())
                .build();
    }
}
