/* ==============================================================================
 * Generated by GitGalaxy (https://github.com/squid-protocol/gitgalaxy) from
 * https://github.com/aws-samples/aws-mainframe-modernization-carddemo at commit 59cc6c2fd7ebd7ef7925cad552a01a4b8b6e4d5e,
 * which is licensed Apache-2.0. This file is derived from that source and was modified in
 * generation; the source's licence terms apply to it (see the LICENSE / NOTICE files and
 * PROVENANCE.md at the root of this example).
 * ============================================================================== */
package com.gitgalaxy.modernized.repository.vsam;

import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import com.gitgalaxy.modernized.entity.vsam.TranRecord;

/**
 * AWS.M2.CARDDEMO.TRANSACT.VSAM.KSDS: READ / WRITE / REWRITE / DELETE are JpaRepository's
 * findById / save / deleteById. Used by app/cbl/CBEXPORT.cbl (INPUT); app/cbl/CBTRN02C.cbl (OUTPUT); app/cbl/COBIL00C.cbl (ENDBR,READPREV,STARTBR,WRITE); app/cbl/COTRN00C.cbl (ENDBR,READNEXT,READPREV,STARTBR); app/cbl/COTRN01C.cbl (READ); app/cbl/COTRN02C.cbl (ENDBR,READPREV,STARTBR,WRITE).
 */
@Repository
public interface TranRecordRepository extends JpaRepository<TranRecord, String> {

    /** EXEC CICS STARTBR + READNEXT: records from a key onward, in key order. */
    List<TranRecord> findByTranIdGreaterThanEqualOrderByTranIdAsc(String tranId, Pageable page);

    /** EXEC CICS READPREV: records from a key backward, in reverse key order. */
    List<TranRecord> findByTranIdLessThanEqualOrderByTranIdDesc(String tranId, Pageable page);

    /** Alternate index AWS.M2.CARDDEMO.TRANSACT.VSAM.AIX (path AWS.M2.CARDDEMO.TRANSACT.VSAM.AIX.PATH, AWS.M2.CARDDEMO.TRANSACT.VSAM.AIX.PATH) on TRAN-PROC-TS, non-unique. */
    List<TranRecord> findByTranProcTs(String tranProcTs);

    // Alternate index AWS.M2.CARDDEMO.TRANSACT.VSAM.AIX (path AWS.M2.CARDDEMO.TRANSACT.VSAM.AIX.PATH, AWS.M2.CARDDEMO.TRANSACT.VSAM.AIX.PATH) is on TRAN-PROC-TS too: findByTranProcTs above.

}